### ISSUE TITLE
Merge various history entries

### ISSUE THREAD

**Issue by ianbrunelli** [Keruspe/GPaste#108]
Hello!

Would it be possible to add a command to merge various entries?

Let's say I have the following items on history:

```
0: LINK1
1: LINK2
3: LINK3
4: LINK4
```

What I want to do is paste all these 4 items, quoting each of them.

It would be great to have a command like `gpaste merge START-END SEPARATOR`. So I run `gpaste merge 0-4 '" "'` and it would add to the history `LINK1" "LINK2" "LINK3" "LINK4`, and then I'd just have to paste it inside quotes...

**Comment by Keruspe** [comment]
Ok, I'm gonna implement it quite soon, I'm thinking of the details atm.

I think the syntax would be more like `gpaste merge '" "' 1 6 7 10` to be able to merge various elements of history without requiring them to be one after another.

The command you pasted would thus be `gpaste merge '" "' {0..4}`

What do you think?

**Comment by Keruspe** [comment]
Another more flexible idea would be

`gpaste merge --decoration '"' --separator ',' 0 1 2` which would output "foo","bar","baz" or maybe `--pattern '"%s"' --separator ','` where pattern could contain %s for the text, %d for the index or such

**Comment by ianbrunelli** [comment]
I really like the `gpaste merge --decoration '"' --separator ',' 0 1 2` idea!

I think the `--pattern` is a bit complicated, but it sure would be great to have. Maybe implement both and we can choose which one is better for a use?

**Comment by Keruspe** [comment]
Merged the version with decoration and separator.
Will release a 3.15.92 RC when glib 2.43.92 is out
