### ISSUE TITLE
pastebin support

### ISSUE THREAD

**Issue by glensc** [Keruspe/GPaste#109]
would be cool if gpaste would support some generic interface to create pastebin from clipboard contents. perhaps activated from keyboard hotkey and/or menu

the configuration should be pretty generic, like execute command with paste being stdin
so could use any pastebin tool, for example https://github.com/glensc/pbin or some could just input some curl command there if there doesn't exist client

**Comment by Keruspe** [comment]
In 3.16.0 there will be a new DBus method `Upload`.

There will also be a new command `gpaste upload` to which you'll have to pass an index, like `gpaste upload 0` to upload what's currently in your clipboard.

There is also a keybinding: `ctrl + alt + u` which does that automatically.

It uses wgetpaste, and the next version of wgetpaste (hopefully released soon) will the only put the url of the paste in your clipboard (currently it adds some extra text)

**Comment by glensc** [comment]
Great. I will be waiting!
