### ISSUE TITLE
Double Monitor setup opens two GPaste dialogs

### ISSUE THREAD

**Issue by bascht** [Keruspe/GPaste#111]
Running version 3.14 of gnome-shell-extension-gpaste (packaged by Fedora) under Fedora 21 with a dual monitor setup.

Opening up the history with `<ctrl>+<alt>+h` opens up two dialog panels. The one on the primary display is functional, but the one on the secondary just stays open even after closing the one on the primary. I can click through it, but cannot close it. (see screenshot)

Let me know if you need more details. :)

![gpaste-double](https://cloud.githubusercontent.com/assets/51264/5434485/ac020f80-8452-11e4-817f-0e93afcc147e.jpg)

**Comment by Keruspe** [comment]
Just out of curiosity, is the problem still there with latest versions of gnome-shell? (as it really seems to be a gnome-shell bug)

**Comment by bascht** [comment]
Yep. Thanks for the bump:
I'm running `gnome-shell-3.14.3-1.fc21` now and the issue is gone. :+1: 

:dancers:
