### ISSUE TITLE
Layout issues in GNOME Shell 3.15

### ISSUE THREAD

**Issue by ianbrunelli** [Keruspe/GPaste#114]
I'm using GS 3.15.91 with the latest version of GPaste and so far no problems, except some minor issues with the layout:

1. The delete button is big. This can be fixed changing its class from `system-status-icon` to `popup-menu-icon`.

2. The search bar is relocated 1px when in focus. This is because the current stylesheet for their search bar has a 1px border while in normal mode and a 2px border in focus, and to compensate this the padding is 1px smaller while in focus.
This can be solved by removing the current stylesshet and using the search bar with the same size as it have on the overview (big, see screenshot), or setting a padding to `#GPasteSearchEntry:focus` (possibility to make it look awkward with themes other than the default).
Edit: Another solution would be to use the same padding and border-width in both states. I think this is better because it would avoid problems with other themes.

3. After hovering the mouse over the search bar it gets a blue background, to indicate it is in focus. However, it stays always blue even if the search bar loses focus or you reopen the menu popup. Is not blue after GS initialization and first launch of the popup, so I've no idea who is guilty here (GS or GPaste).

![Screenshot](http://i.imgur.com/dwOOcFe.png)

**Comment by Keruspe** [comment]
Heh, I had the same problem as you with the delete button being big, but this commit fixed it: https://github.com/Keruspe/GPaste/commit/2a153bf5d7b52fd121fa8cdf8fe45dd10d6ba3cf

Are you sure your extension is up to date?

For your point 2, should be fixed by https://github.com/Keruspe/GPaste/commit/1933d7f098e1e6a7667d099305df5591251fa481 thanks for the hints

Regarding the search bar stuck in blue, I'm experiencing the same and have not tried to track that down yet.

**Comment by Keruspe** [comment]
I switched to popup-menu-icon for your point 1 as it fixes the issue here as well and makes more sense anyway

**Comment by Keruspe** [comment]
The culprit for point 3 is https://github.com/Keruspe/GPaste/blob/master/src/gnome-shell/searchItem.js#L83-L85

Will see what's missing there

**Comment by ianbrunelli** [comment]
Sorry, I thought I was looking at the code in my `master` clone, but it was code from version 3.14...

Great to know you were aware of these issues!

Also, one more thing: do you thing is there any way to make the popup max-height be equal to the available y area in the screen and then make the entries list scrollable if the area isn't enough to display all of them?

**Comment by Keruspe** [comment]
https://github.com/Keruspe/GPaste/commit/3f6541733ae45adce86ba311858d1abc81c77a4e and https://github.com/Keruspe/GPaste/commit/15ecdd8d27789a1e4224cee46f0c22aaed7fb30c should address the third issue.

Thanks for the great report

**Comment by Keruspe** [comment]
For your last question, I wish it could be doable, but using the native gnome-shell menu items there is no way at all of having a scrollable view :-/ (that's where the max-displayed settings comes from...)

Closing as the three initial reports have been addressed
