### ISSUE TITLE
error in Makefile

### ISSUE THREAD

**Issue by aboettger** [Keruspe/GPaste#117]
master* ± make
Makefile:3675: *** missing separator (did you mean TAB instead of 8 spaces?)

**Comment by Keruspe** [comment]
How did you generate the makefile?

**Comment by Keruspe** [comment]
(and which distribution)
You're probably just missing some dependency :)

**Comment by aboettger** [comment]
Ubuntu 15.04

./autogen.sh
./configure
make

http://paste.ubuntu.com/10710638/

**Comment by Keruspe** [comment]
Did you install those packages?

https://github.com/Keruspe/GPaste/blob/master/README.ubuntu

**Comment by Keruspe** [comment]
And can you please upload the generated Makefile somewhere?

**Comment by aboettger** [comment]
http://paste.ubuntu.com/10711114/

**Comment by Keruspe** [comment]
Oh, right, there's a dependency missing in this README

Try installing appstream-glib ans regenerate the Makefile, it should work better then

**Comment by aboettger** [comment]
Nothing.
My steps:

sudo apt-get install libappstream-glib-dev
rm -rf ~/src/GPaste
cd ~/src
git clone git@github.com:Keruspe/GPaste.git
cd GPaste
./autogen.sh
./configure --sysconfdir=/etc
make
Makefile:3675: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.

**Comment by Keruspe** [comment]
Hmmmm, looks like the package providing appstream-xml.m4 is appstream-util actually, on ubuntu

**Comment by aboettger** [comment]
with "appstream-util" it works

**Comment by Keruspe** [comment]
fixing the README, thanks
