### ISSUE TITLE
Increase Max history size to 1000?

### ISSUE THREAD

**Issue by fnewio** [Keruspe/GPaste#118]
Hi!

I'm in Debian Jessie with GNOME 3.14, and in general would like to 'feature request' that the Max history size be increased from the current 255 to 1000 :).

A number of other Linux clipboard managers go up to it (though most are 100, and I find that abysmal when you want to go back a few weeks/months worth!), and one, Keepboard, even manages 10,000! Over the years 1000 has always served me well (on different platforms).

But in the meantime, i'm wondering if there's a way for me to tweak any hidden .config files to change the value from 255 to 1000 also?

In the source I see it clearly it in gpaste-settings-ui-stack.c, but on my stable Debian system it's just too much hassle to try and manually compile and install on my system (and kind of insane to try and update a stable debian GTK 3.14 environment to 3.16 to even install the shiny new 3.16+ version of GPaste), so I'd be patient to wait until the feature change eventually made its way into debian repos, or again, if there's some magical .config way to do it in the binaries themselves already!

Thank you :).

**Comment by Keruspe** [comment]
Hi,

Indeed, I almost forgot about this upper limitation.
I'll sure bump it for next releases.

In the mean time, you can edit the installed settings schema installed in `/usr/share/glib-2.0/schemas` (or something like that), and run glib-compile-schemas `/usr/share/glib-2.0/schemas`and it should do the trick. Just look for the `max-history-size`setting.

Note, though, that the entire history is loaded in ram.

**Comment by fnewio** [comment]
Ahhhh, right! I'm still a bit new with linux so didn't know about this folder [and that command to reflect the changes, thank you] :). So the file in question is `/usr/share/glib-2.0/schemas/org.gnome.GPaste.gschema.xml`. I've set 'max' to "1000" and even <default> to 1000 (to try to be sure), saved it in sudo nano, done glib-compile-schemas, restarted gnome shell, disabled and re-enabled the extension, done gpaste dr, then finally restarted linux entirely, and in the gui options it still does't allow more than 255 in the box (via reset or plus button). Maybe it is doing 1000 anyway! I wonder how I can work that out...if nothing else, I can try a laborious paste of 256+ numbered items (code up some script to ctrl+c each line) and see if 256.+ AND 1. and 2. are all in search results, then I'll know.

And then: a related GUI bug: the whole max-displayed-history-size thing in the GNOME extension isn't fleshed out for when it's more than the default 20 (tl;dr: it needs a scroll bar :) ). Say you set it to 200 or something: the UI list doesn't have a scroll bar and associated fixed pixel height of the box area, so the buttons down the bottom are obscured into off-screen limbo (like Inception depths of limbo here :P) and yeah everything else associated with no scroll bar happens too: arrow button'ing down just starts an expedition into off-screen limbo and also it would be great to be able to, when doing an up arrow while in the default top search bar, go to the BOTTOM of the scroll bar'd list (then bottom arrow from bottom item go back up to the dop, going down from top again).

Happy coding :).

**Comment by Keruspe** [comment]
You can bypass the settings gui by using dconf-editor, and go into org gnome GPaste, you'll find the raw settings values here.
Yep, it definitely needs a scrollbar. Unfortunately, gnome-shell menus don't support scrollbars :-/
Hopefully the search helps with that.

Note that in GPaste 3.16, a new gui tool to manage the history is available as a preview. This one will have a scrollbar & co.

**Comment by fnewio** [comment]
Thanks. Ah right so that was just the dconf stuff on the file system (simple XML, huh), got it! Didn't think of searching dconf. Anyway yep I made a klunky script to automate inserting 300 items numbered 001 to 300 into clipboard one by one and they're ALL in the history as well as the existing items I had before it, so clearly the 1000 number is applying - AWESOME! Yeah search will more than do for now (I'll actually use it in tandem with clipit for now then, which by default has a glanceable/scrollable 'first 100' but not as good searching), and I look forward to 3.16+ when I assume it finds itself in Deb repos :).

**Comment by Keruspe** [comment]
Just increased default to 100 and max to 65535, will release 3.16.1 soon

**Comment by Alyetama** [comment]
> 65535

May I ask why the max is this specific number?  Is there a reason to prevent the user from choosing a number above that?
