### ISSUE TITLE
Automatically paste item after selecting it

### ISSUE THREAD

**Issue by fnewio** [Keruspe/GPaste#119]
I've discovered GPaste after trying about 10 other clipboard Linux tools (on Debian), and clearly fate has kept the best one till last! :) (Sigh.)

But there's only ONE main small but important feature lacking (that I can't hack myself in the source anyway ... I'm no coder, and this one's a bit too complicated to work out...), and it's this:

When you 'select' an item from the history list (and this should apply to all GUI interfaces - when browsing the GNOME extension's history list with the arrow keys then pressing <ENTER>, clicking the same desired item with the mouse, or doing the same after searching in the list): it doesn't paste the item for you... (like it would make sense to, as this all is just a giant searchable replacement for 'Ctrl+V' after all, where you're just 'Ctrl+V'ing' an 'old' item that you're fishing around for instead of the current one!)

It's something that clipit can do, but GPaste isn't doing (at least on my Debian Jessie with GNOME 3.14).

If added in (at least as an option), this will make GPaste a truly complete awesome all-round Linux clipboard tool :).

Because currently, you have to do Ctrl+V as an EXTRA step after selecting the desired item which is kinda klunky and an unnecessary extra step if you want to use it in this way! Automatic paste will make it very slick.

Thanks for your consideration and the ongoing dev work! The GUI of the GNOME extension is really awesome.

**Comment by Keruspe** [comment]
There used to be such a feature, but unfortunately, clipboard handling in xorg in too broken for a clipboard manager to do that automatically. Clipit does it but it does it really wrong and it just happen to randomly work, or not.

Long story short, here is why it can't work:
When you copy something, you don't give to the xorg server the new contents of the clipboard. Instead, you just say "I'm the new owner of the clipboard". This part is cool.
The uncool part is that it works the same for pasting. The clipboard don't send its contents to whatever the active window is. The active window has to explicitely request the contents to the current owner.

If you want to paste something in firefox, gedit, or whatever other tool, here is what used to happen when we did automatic paste:

While GPaste is acting, the active window is a virtual window of GPaste (that's how it can get clipboard events).
GPaste tells the xorg-server to fake the event that the user pressed ctrl with a certain delay (which is highly unreliable given it depends on the latency of the computer).
GPaste tells the xorg-server to fake the V, still with a delay (so that it happens when the active window is the one you want to paste stuff in)
GPaste tells the xorg-server to fake the release of the keys.

First problem: the unreliable delay.
Second problem: ctrl-v is not a standard way to paste things. Shift-Insert is (and we actually used shift-insert and not ctrl-v). Some software won't use ctrl-v, but ctrl-shift-v, or other stuff.
Some software might react in a different manner to Shift-Insert too.

There is no way to just tell "paste" with xorg, we can only try to fake keyboards event, which fail really often.
I wanted to provide reliable feature so I dropped this unreliable one.
I'm really sorry about this, as I'd really want it too :-(

All we can do is wish that wayland will do stuff better.

**Comment by Keruspe** [comment]
Note that if you find a reliable way to request a paste, I'd be happy to integrate it. Like a command line software or so.

**Comment by fnewio** [comment]
I appreciate your informative and detailed explanation so much :).

That all totally makes sense. So it seems clipit just does shift-insert, and haha yeah in nano, it definitely *doesn't* do paste :P.

But the thing is though, I already know that, so I just know not to use it in nano! But one idea may make it 'worth it' and even improve on the whole situation / kinda be win/win. For your consideration :).

You could make it an advanced option for users who are willing to live with its klunkiness (given indeed 90% of common apps work just fine with it after all, and clipit hasn't failed me in terms of delay at least, so it may be 'good enough' for some folks :P), titled like: 'Automatically paste selected item (Experimental)'[/may break things/advanced)], and it could work two ways:

1. Just do blanket shift-insert like clipit and the user is expected to know when it works, when it doesn't do anything, and when it just breaks things (it's opt-in, with a warning after all). But even better:

2. As long as it wouldn't be too taxing to manage, have simple window rules-based customization, i.e., 'if winClass is [gnome-terminal-server.Gnome-terminal,someother.Similarwindowclass,another.One,] do ctrl-shift-v else do shift-insert' - and halleluja, maybe one day I could even paste items into nano from history in a SINGLE click!

I mean, I want it so bad that I feel if I could only script up (in SOME tool), to the effect of: 'watch GPaste GNOME extension, and when window closes [and maybe, 'and when clipboard just got modified', so it doesn't do it when I don't actually select an item], emulate shift-insert'.

I've fooled around a lot in xdotool, wmctrl, and the really awesome [AutoKey](https://code.google.com/p/autokey), so almost feel this would be possible given I know what else you can do that's awesome, so hey maybe it it can be done even for me right now (while I'm stuck in 3.14 for a while).

In fact, maybe all I have to do is 'monitor when clipboard changes [well, when it's updated BY GPaste anyway, if that's possible to determine!] - and when it does, automatically do shift-insert'.

And if I'm lucky I could EVEN script that to differentiate by current window class (as hinted above), doing ctrl-shift-v in terminal, and other exceptions as I discover them. It's a bit over my non-programmer skills, but I've got a lot of determination :). Any ideas? And I guess the same thing could easily enough be coded into GPaste as an advanced option if you wanted too :).

**Comment by fnewio** [comment]
Another interesting idea (wouldn't apply for me now but you could implement it into the new version): 'Custom command on item selection' - an option to enable an advanced user to enter any command they want upon selection - so e.g. they could put in: `xdotool key ctrl+v` or, at the expense of a slight delay but making it extend to non-ctrl-v apps and to prevent non-paste behavior for apps, /path/to/custom/script, which, they could do the `if winClass is [gnome-terminal-server.Gnome-terminal, someother.Similarwindowclass, another.One,] do ctrl-shift-v else do shift-insert` thing like I mentioned!

Again though, that would only apply to the new updates and not something I could do in the mean time..

**Comment by elgalu** [comment]
FYI [ClipIt](https://github.com/CristianHenzel/ClipIt) manages to do this by, apparently, simply sending the `CTRL+V` [see here](https://github.com/CristianHenzel/ClipIt/issues/45#issuecomment-171535747).

**Comment by Keruspe** [comment]
GPaste was doing exactly that too at some point, but it really isn't that
simple. Not all software support this combination and it's really racy. It
caused lots of bugs

**Comment by elgalu** [comment]
Ah ok, I only tested it on Chrome, Firefox, Sublime Text, vscode, the terminal, Guake and some Gnome apps to be fair.

**Comment by goncalossilva** [comment]
@Keruspe Even though it's dirty and hacky I'd love to work on a extension that "adds" this to GPaste. This feature alone would keep me on X11 for now.

I have no experience working with this, but I have GPaste's old code. My question is: is there an event that the GPaste Daemon fires when a history entry is chosen? How can I bind to it?

If not, I'm thinking of listening for "owner-change" and check the owner itself.

**Comment by goncalossilva** [comment]
Hum, seems like the only event is "Update", but that happens either when a GPaste entry is selected or a regular Copy action happens. Would love a pointer if there is one.

**Comment by Keruspe** [comment]
I could add a signal which is emitted when a new item is selected

**Comment by goncalossilva** [comment]
That would be amazing!

**Comment by Keruspe** [comment]
Can you open another issue so that I ping you when it's ready?
I'm currently working on a little rework of some parts of the API, will add it once I'm done

**Comment by goncalossilva** [comment]
Done: https://github.com/Keruspe/GPaste/issues/223. Looking forward to this, and thanks!

**Comment by diegozaloto** [comment]
It would be great to have this feature!

**Comment by JaredStemper** [comment]
Hi @Keruspe, I'm a new user to GPaste and was reading through the various troubles implementing this feature (on Xtest at least, as I'm not sure Wayland has functionality for this still) and was wondering if this compromise would make sense to you.

Given that the two primary issues in reliability stem from variance in knowing which keys to press and the the delay to use (based primarily on hardware and current load), would it be reasonable to assume users could define these variables for their most common use case? e.g., users who opt into such a setting could set ctrl+shift+v 

I was hoping this approach would take some measure of effort off of the development side to "guess" the user's need.
