### ISSUE TITLE
Feature request (for new GUI tool): option to number the items

### ISSUE THREAD

**Issue by fnewio** [Keruspe/GPaste#120]
One thing I've often appreciated in a good clipboard history app (in windows, os x and now linux) is if it can number the items in the history list (like an index) - in both the initial scrollable list, and even in the insta-filtered search results. No. 1. being the top one, 255. being the earliest etc.

E.g.:

Say I'm searching for an old PAIR of items I had adjecently copied into the clipboard (a pair of obscure commands to use together, a *cough* username and password), I remember some text of the FIRST item (so can retrieve it) but not the one that accompanied it, and if I can know the NUMBER of the one I do remember, I can then use that to reference the second by at least browsing down to it in the numbered list (or this would be even better too - being able to have search queries also REFERENCE the numbered index so if the elusive item I'm looking for is clipboard item no. 329, rather than having to scroll all the way down manually to 329 I can just type '329' and as I type it will also return numbered items containing 3, then 32, then 329 respectively :) ).

So yep - that's it. Would be really great. You can probably tell I use clipboard history as my life insurance/SOS...

Oh, indeed, clipit numbers it (in its browsable list). But, it's not integrated with its search, and only shows index numbers in its browsable list.

**Comment by Keruspe** [comment]
They are now displayed (in current git version, so will be in 3.18).

They are not yet included in search, but they will be soon-ish.

**Comment by Keruspe** [comment]
They are now included in the search results :)
