### ISSUE TITLE
Frequent disk writing after check on "save history" option

### ISSUE THREAD

**Issue by amitbha** [Keruspe/GPaste#122]
Ubuntu gnome 15.04
gnome-shell 3.14.4
gpaste 3.14

After check "save history" option, every copy causes write-once.
The clipit app, no longer maintained, saves the history quietly, in contrast.
It's not a big deal, but I'd appreciate if it could be solved.

**Comment by Keruspe** [comment]
What do you mean by "saves the history quietly"?
How would you expect GPaste to save it?

**Comment by Keruspe** [comment]
I just read clipit sources and it seems to write the file each time something is added to the history too, so I'm even more confused about what you mean.

**Comment by amitbha** [comment]
Sorry for my terrible english, :-(
I just notice that, when using gpaste, every copy cause the HDD-LED flash once, but the clipit not like that.

**Comment by Keruspe** [comment]
Not sure why it flashes with GPaste and not with clipit, but both rewrite the history file every time you copy something (so both write to disk).
Maybe GPaste take longer because you have a bugger history or something like that?

**Comment by amitbha** [comment]
I uncheck "save history" and re-login, all history cleared. But things unchanged.
I switch to clipit, and watch carefully. You're right, it writes too, but the LED flash slightly, more difficult to detect. Seems imposibble, my delusion?!

Is it possible to privide an option "save history on exit"?
If so, frequent copy operation won't lead to frequent disk writing.

**Comment by Keruspe** [comment]
The problem is that such an option would be unreliable.
Systemd stop very fast these day, and nothing can assure us that we'll be one of the first apps to exit.
We could even exit once / is remounted read-only, and then we couldn't write at all.

**Comment by amitbha** [comment]
I use fs2ram to reduce disk read / write and it can preserve tmpfs contents across reboots. It seems to use umount script to save the tmpfs contents before shutdown. Shortcoming is slowing down the shutdown sometimes.
I don't know if this mechanism is suitable for Gpaste.

**Comment by Keruspe** [comment]
Then you probably can use fs2ram with GPaste using a tmpfs, I guess.
GPaste only writes to ~/.local/share/gpaste/
I prefer not to support a feature I don't find reliable inside of GPaste itself.

Please keep in mind though that no matter what the LED on your computer tells you, clipit writes just as much as GPaste to your disk.
