### ISSUE TITLE
Display more characters on the search provider

### ISSUE THREAD

**Issue by ianbrunelli** [Keruspe/GPaste#124]
On the search provider, the number of characters in the results is the same as in the extension's popup. It shouldn't be, because the Overview has a lot more of horizontal space.

The entry `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua` displays this:

![captura de tela de 2015-06-13 11-16-22](https://cloud.githubusercontent.com/assets/5755892/8144625/92f6a872-11bd-11e5-93fc-e59d5f27a9a6.png)

**Comment by Keruspe** [comment]
When I tried I had some weird bugs, but now it seems that gnome-shell handles the max size by itself just fine.
Should be fixed

**Comment by ianbrunelli** [comment]
Thank you!
