### ISSUE TITLE
please add a Cinnamon version of the applet

### ISSUE THREAD

**Issue by calestyo** [Keruspe/GPaste#126]
Hey.

It would be great if you could add a version of the applet that works for cinnamon.

Thanks,
Chris.

**Comment by Keruspe** [comment]
Hi,

Isn't cinnamon supposed to be compatible with gnome-shell?
Did you try to use the gnome-shell extension with cinnamon?
Which error does it give you?

**Comment by calestyo** [comment]
Hey.

Well I guess that compatibility is not a "full compatibility"... plus Cinnamon seems to strongly go it's own ways....

Anyway I tried it, when just symlinking it in ~/.local/share/cinnamon/applets/ or ~/.local/share/cinnamon/extensions/ on get's e.g. a:
error t=2015-06-19T17:15:52.786Z [Applet "GPaste@gnome-shell-extensions.gnome.org"]: File not found: /home/calestyo/.local/share/cinnamon/applets/GPaste@gnome-shell-extensions.gnome.org/applet.js
error t=2015-06-19T17:15:52.787Z Could not load applet GPaste@gnome-shell-extensions.gnome.org

When copying the whole extension dir into there:
error t=2015-06-19T17:23:16.707Z [Extension "GPaste@gnome-shell-extensions.gnome.org"]: Missing property "cinnamon-version" in metadata.json
error t=2015-06-19T17:23:16.708Z Could not load extension GPaste@gnome-shell-extensions.gnome.org
error t=2015-06-19T17:24:31.810Z [Extension "GPaste@gnome-shell-extensions.gnome.org"]: Missing property "cinnamon-version" in metadata.json
error t=2015-06-19T17:24:31.810Z Could not load extension GPaste@gnome-shell-extensions.gnome.org


So I guess one would need to make a copy of the applet and change some things to the cinnamon way.
I also found:
http://cinnamon-spices.linuxmint.com/applets/view/27
but that seems to be only loosely maintained,... so maybe you can simply merge that and keep it up to date with any upstream changes?

Thanks,
Chris.

**Comment by calestyo** [comment]
There seems to be a somewhat newer version:
http://cinnamon-spices.linuxmint.com/applets/view/214 ... anyway, I still think that it would probably the best if this would be maintained upstream :-)

**Comment by Keruspe** [comment]
Thanks for the pointers :)
Can you try adding a "cinnamon-version" field to metadata.json with your cinnamon version ?

**Comment by calestyo** [comment]
No help either,...:
error t=2015-06-19T18:10:57.072Z [Applet "GPaste@gnome-shell-extensions.gnome.org"]: File not found: /home/calestyo/.local/share/cinnamon/applets/GPaste@gnome-shell-extensions.gnome.org/applet.js
error t=2015-06-19T18:10:57.073Z Could not load applet GPaste@gnome-shell-extensions.gnome.org


Seems all official applets/extensions have this

**Comment by Keruspe** [comment]
Do `/home/calestyo/.local/share/cinnamon/applets/GPaste@gnome-shell-extensions.gnome.org/` actually exist ? (this is the folder the extension files should be in)

**Comment by calestyo** [comment]
Yes it exists, ... AFAIK it's the one where the extensions should be in and I copied the gnome shell version of the applet into that location (and also to ...../extensions/).
If I don't copy them there, they don't show up in cinnamon's control center either.

**Comment by calestyo** [comment]
Anything new here? :)

**Comment by Keruspe** [comment]
I've been way more busy than I expected lately so I couldn't really work on GPaste.

I still haven't any system running cinnamon either.

There's still a few things I want to do on my TODO before I try to do anything about this. This might not be ready for 3.18, but will sure be for 3.20 at most. Any help appreciated, I'm pretty sure there's not a lot of conditionals to add to the gnome-shell extension for it to run on cinnamon

**Comment by calestyo** [comment]
Great :-) I'm looking forward to it =)

**Comment by Keruspe** [comment]
I started working on this, moving all the common code to a common location.
I still need a little refactor to extract the gnome-shell specific things from one last file, and then the only blocker will be this issue: https://github.com/linuxmint/Cinnamon/issues/4656

**Comment by calestyo** [comment]
+1

**Comment by Keruspe** [comment]
@calestyo Now you can try to convince upstream cinnamon to fix this issue :)

**Comment by Keruspe** [comment]
I was willing to do that as long as the majority of code could be shared with gnome-shell.
As I do not use cinnamon nor have I access to some cinnamon computer on a regular basis, and not being able to reuse that much code, I prefer not to do that at all, rather than providing something of poor quality.

There seem to be a new version of the extension you pasted earlier though.

I wouldn't mind someone contributing a cinnamon version here, but this person won't be me.

**Comment by calestyo** [comment]
Hey... coming back on this:

Have you seen this: https://github.com/Feuerfuchs/GPaste-Reloaded-Cinnamon-Applet ?

Would it be something that could be merged into gpaste?
