### ISSUE TITLE
autogen.sh will return false if no argument is passed

### ISSUE THREAD

**Issue by ianbrunelli** [Keruspe/GPaste#127]
[Line 75](https://github.com/Keruspe/GPaste/blob/e0dc5e4a1c7f2f070bb44ec3550704740a545e7d/autogen.sh#L75) will make `main()` return `false` if no argument is passed when running `autogen.sh` (if `"${#}" != 0` is `false`). This can be fixed by adding `|| return 0` or something like that to the end of that line.

**Comment by Keruspe** [comment]
Nice catch, thanks!

Should be fixed by 02f16168a11cc1f61d86ed9b204e4b77c47dd76e
