### ISSUE TITLE
Detect growing lines doesn't detect them in some apps

### ISSUE THREAD

**Issue by TravellingGuy** [Keruspe/GPaste#128]
I'm having a problem with the detect growing lines option in some apps. Specifically, it seems to happen only in new Gnome 3 apps.

For example, in gedit (3.16), gnote (3.16), epiphany (3.16) and Chromium (v45), the detect growing lines option doesn't detect growing lines at all, and ends up copying:
42: Is your
43: Is you
44: Is yo
45: Is
46: I

Other apps, Firefox (v40), roxterm (3.1.5) and gnome-terminal (3.16) don't have this problem, and I can select text fine, and it will only copy the final select to the clipboard.

If I turn off "Primary select affects history" option, the problem goes away, but I have a tendency to use the primary selection quite often, so I prefer to leave it enabled.

**Comment by Keruspe** [comment]
Hmm, I can indeed reproduce the problem, will try to fix asap

**Comment by Keruspe** [comment]
Ok, this regression has in fact been there since version 3.16, as it seems.

517f6c12be61c7efc80c7ae351074c64b6b675d6 should fix it properly.

Will make a new release of gpaste 3.16 and 3.18 later this week, thanks for reporting!

**Comment by Keruspe** [comment]
@TravellingGuy released 3.16.3.1 and 3.18.1 yesterday, please reopen if the issue is still not fixed with either of those, but I'm pretty confident as it works as expected here now

**Comment by TravellingGuy** [comment]
@Keruspe I will do that. I'm running Debian unstable, so it shan't be too long before it shows in the Debian unstable (or experimental) repo.

**Comment by TravellingGuy** [comment]
@Keruspe Confirmed that 3.18.1 works as expected now. Thanks a bunch for the quick turnaround.
