### ISSUE TITLE
[idea] Share clipboard history over the network

### ISSUE THREAD

**Issue by gergelypolonkai** [Keruspe/GPaste#129]
I use GNOME on two machines, my desktop and on a notebook. As I often share tasks between the two, I thought it would be nice to share the clipboard content, too. Of course, this brings in a lot of questions including security ones, and the whole concept needs polishing. I just wanted to post it here for a discussion.

**Comment by Keruspe** [comment]
I think the idea had been suggested a while back, and it came back to my mind a while ago actually.

For this to work safely, I'll first need to address my TODO item about gpg support (GPaste basically would never write clear text files but encrypted ones using a given key). Once that is done, it could be done.

If I ever do this though, I want to do this properly by allowing people to install the server part on their own servers first, and then maybe provide some kind of official location, but then there is the server costs question.

Anyways, that definitely could happen some day, but it's not trivial for now at least.

**Comment by gergelypolonkai** [comment]
If you use GNOME Online Accounts, you can use many remote file storages
like ownCloud, and the file could also be stored on a mounted network
drive, so I don't think storage is the big deal.

Using GnuPG is not *that* hard, if I have some free time I can make a
prototype (hopefully will happen next week).

Another idea for sharing it is like a network based notification, ie.
broadcast the new item in the daemon over the local network (of course,
encrypted), so other computers can access it. This, on the long run, may
allow sharing clipboards within teams, too.

**Comment by Keruspe** [comment]
Using gpg to encrypt a file is easy. Using gpg to write directly to an encrypted file without having the whole contents before is not that trivial iirc.

What would be needed here is some subclass of GOutputStream (https://developer.gnome.org/gio/stable/GOutputStream.html) which would handle the gpg encryption automatically.

Note that the two only methods used by GPaste are write_all and close so a standalone class using a GOutputStream and having just these two methods would bo ok too.

Regarding GOA, I don't think that would be sufficient. I'm not sure whether there's some kind of "file changed" notification or not. Imagine two computers sharing the same history over network. One would expect that when the first one copies something, it appears on the second one right after.

**Comment by Keruspe** [comment]
Actually, implementing a GConverter (https://developer.gnome.org/gio/stable/GConverter.html) would be enough

**Comment by gergelypolonkai** [comment]
Yes, storing encrypted history could be hard if you use append. If you not consider online sharing, though (here, by online, I mean always up-to-date), append is not required.

Online sharing using **any** service brings in sync problems, as most online services doesn’t have reliable “file changed” notifications. That’s why I thought of broadcasting instead of full history sharing, which could work great in local teams. But this would mean that remote colleagues won’t benefit from GPaste…

**Comment by Keruspe** [comment]
I don't get what you mean there.

My idea is pretty simple: having a server components to which you push the history on update, which notifies others to tell them it has changed, and the others just redownload it.

There's no appending here.

This way you can install a gpaste server locally, or remotely.

**Comment by gergelypolonkai** [comment]
Now I get it! I was thinking about some simple file sharing over whatever service the user chooses (Dropbox, Google Drive, ownCloud, whatever). Your idea sounds much better, although requires much more coding.

**Comment by Keruspe** [comment]
the problem of just using some file sharing service, is this:

Imagine three people share the same history. They arrive at work at 9am.
The three of them load the current state.
One copies a lot of things, from foo1 to foo9999 in the day
The second copies from bar1 to bar9999
The third doesn't work much this day, and only copies baz1 to baz9.
Those three people finish at 6PM, and the third one is the last one to copy something.

The day after, when the three people start working, they lose everything that has been copied the day before, except from baz1 to baz9 since it's the last one to have copied something and he never got notifications that the others copied something.

**Comment by gergelypolonkai** [comment]
…unless you merge them somehow. Which, of course, is not trivial. Maybe it would be possible if the items are timestamped.

**Comment by kapouer** [comment]
..unless you use a remote database to store the clipboard.
https://github.com/Keruspe/GPaste/issues/155 could pave the way, supporting a local sqlite db by default, or a remote db.

**Comment by Keruspe** [comment]
After giving it more though, I don't think this should be part of GPaste.
Another daemon listening to DBus signals and synchronising stuff across network could be doable, but it really should be a separate project which would use GPaste.
