### ISSUE TITLE
gpaste-ui 3.18.1.1: `about` action focuses main window

### ISSUE THREAD

**Issue by heftig** [Keruspe/GPaste#132]
The `about` action brings up gpaste-ui and has it display the "About GPaste" window, but it immediately refocuses the main window.

**Comment by Keruspe** [comment]
It's even worse, the right window is actually focused, but the main window appears on top of it.
I didn't manage to find the cause yet

**Comment by Keruspe** [comment]
Ok, this is now fixed with 5ca1d4fa20a66c5b3cc43fd85f12ab19f09bef9b
