### ISSUE TITLE
gpaste-client 3.18.1.1 zsh completion broken

### ISSUE THREAD

**Issue by heftig** [Keruspe/GPaste#133]
Attempting to complete `gpaste-client` arguments just uses the default file completion, while attempting to complete `gpaste` arguments causes errors:
```
(eval):1: _gpaste: function definition file not found
(eval):1: _gpaste: function definition file not found
(eval):1: _gpaste: function definition file not found
(eval):1: _gpaste: function definition file not found
```

zsh 5.1.1

**Comment by Keruspe** [comment]
I had the same issue, but it does not seem to be GPaste's fault.
I couldn't find the root cause, but removing ~/.zcompdump fixed it here :/

**Comment by heftig** [comment]
You're right - must be a stale cache.
