### ISSUE TITLE
xdm + xsession + running from wm -> couldn't connect to gpaste daemon

### ISSUE THREAD

**Issue by neg-serg** [Keruspe/GPaste#134]
Hello, I've get following error

```
** (gpaste-client:19548): CRITICAL **: Couldn't connect to GPaste daemon: GDBus.Error:org.gnome.GPaste.Error: no content to add
```

 and empty output of gpaste-client command when I've tried to run gpaste from window manager after switching from xinit to xdm + xsession

For now I'm using arch linux with systemd 227-1 and gpaste-git 3.18.2+98+g1fb2a9f-1
Version of xdm is xorg-xdm 1.1.11-5

Switching to less new versions like 3.16 did't helps.

I am really want to use xdm because of lightweight and good visual design with properly customizations

My xinitrc/xsession is here: http://sprunge.us/faUd

**Comment by Keruspe** [comment]
Hi,

What is the value of DBUS_SESSION_BUS_ADDRESS env variable?

If you unset it, does it work?

**Comment by neg-serg** [comment]
[code]
echo $DBUS_SESSION_BUS_ADDRESS
unix:path=/run/user/1000/bus

ls -l /run/user/1000/bus
srw-rw-rw- 1 neg neg 0 Oct 20 11:33 /run/user/1000/bus
[/code]

It continue to work only from terminal.

**Comment by Keruspe** [comment]
So, you say it works fine when you run it from a terminal, right?

When exactly does it fail?

**Comment by Keruspe** [comment]
Ok, I think I managed to reproduce your error.

Should be fixed in git now, please reopen if it's not
