### ISSUE TITLE
Pastebin service

### ISSUE THREAD

**Issue by WyRe** [Keruspe/GPaste#135]
Hi guys! Congrats for this awesome software :P 

I would like how could I setup a pastebin service to upload my strings, and how would I get the links when I'll do that :D 

Thank you so much, and sorry if this post causes some inconveniences :P

**Comment by Keruspe** [comment]
Hi,

If you install wgetpaste (http://wgetpaste.zlin.dk/) which is probably packaged for your distribution, hitting "<Ctrl>U" will upload the last thing you copied and copy the url.

Using the graphical user interface (gpaste-client ui) there's a button on the right of each item to do just that too

**Comment by Keruspe** [comment]
@WyRe Was that what you were looking for?

**Comment by WyRe** [comment]
@Keruspe yes it was :P but could u be more specific about upload things hitting "U" key? only that key? or something like shift+u ?

**Comment by Keruspe** [comment]
Heh, it was actually interpreted as html by the github interface ><

I meant `<Ctrl><Alt>u`

**Comment by WyRe** [comment]
damn divs xD 

Thank you so much :P
