### ISSUE TITLE
Extension search-entry hover

### ISSUE THREAD

**Issue by zagortenay333** [Keruspe/GPaste#138]
Is there any way to get rid of the hover effect. The entry is placed inside a `.popup-menu-item` and picks up it's hover effect, which looks pretty weird.

**Comment by Keruspe** [comment]
Just to be sure, you want to get rid of the popup-menu-item hover for the search entry?

**Comment by zagortenay333** [comment]
Yeah, I think it looks pretty weird.

**Comment by zagortenay333** [comment]
Btw, is there any way to bring this entry into focus via shortcuts?

**Comment by Keruspe** [comment]
`<Ctrl><Alt>h` should popup the menu with focus in the search entry

**Comment by zagortenay333** [comment]
Oh, sweet!

**Comment by Keruspe** [comment]
This is now fixed

**Comment by zagortenay333** [comment]
Thx
