### ISSUE TITLE
image clipboard from cli?

### ISSUE THREAD

**Issue by carnager** [Keruspe/GPaste#139]
Is it possible to add an image to gpaste history via cli interface? or does it only work by using UI applications?

**Comment by zeltak** [comment]
Hi!

i very much second that, been wanting to ask this myself

Z.

**Comment by Keruspe** [comment]
It's not possible for now, but I'll sure add it

**Comment by Keruspe** [comment]
This is now implemented with 2185327af3be2b9efefbd5c45380701778845bee

`gpaste-client file foobar` will still add the contents of foobar as text if it's valid utf8, otherwise it iwill consider foobar as an image.

**Comment by clemera** [comment]
@Keruspe Is it possible to add other files to the clipboard using the cli? When copying files in the File Manager they appear as `[File] ...` items but I wasn't able to add them from the gpaste-client.

**Comment by clemera** [comment]
@Keruspe Or maybe this is possible via dbus? Any pointers are much appreciated
