### ISSUE TITLE
RFH systemd user units and debian package

### ISSUE THREAD

**Issue by kapouer** [Keruspe/GPaste#141]
Hello,
i'm preparing gpaste 3.20 debian packaging for upcoming availability of gnome 3.20 in debian.
However i wonder if i'm supposed to do something with the systemd user units ? I can't really
install them using dh-systemd - it only deals with system units.
If you have any insight... that would help me :)

**Comment by Keruspe** [comment]
Hi,
Those are actually mostly used for proper namespacing in logs.
Several other packages provide those now, like evolution-data-server, evince, gvfs, dbus, pulseaudio...
You probably want to go give a look at how that's handled for those.

**Comment by kapouer** [comment]
Thanks for the pointers.
