### ISSUE TITLE
Compiling GPaste for Gnome Shell 3.18

### ISSUE THREAD

**Issue by paulwellnerbou** [Keruspe/GPaste#142]
I am trying to compile GPaste for my Ubuntu Gnome with 3.18, but I am getting this error:

```
./autogen.sh 
libtoolize: `build-aux/ltmain.sh' is newer: use `--force' to overwrite
libtoolize: `m4/libtool.m4' is newer: use `--force' to overwrite
libtoolize: `m4/ltoptions.m4' is newer: use `--force' to overwrite
libtoolize: `m4/ltversion.m4' is newer: use `--force' to overwrite
bindings/vapi.mk:29: error: ENABLE_VAPIGEN does not appear in AM_CONDITIONAL
Makefile.am:87:   'bindings/vapi.mk' included from here
autoreconf: automake failed with exit status: 1
```

What do I need to compile GPaste? Or is there a binary/dpkg for Gnome Shell 3.18 released somewhere?

Thank you.

**Comment by Keruspe** [comment]
I don't know if there are packages for ubuntu but you should use a release tarball and not run autogen.sh, it would probably make your life easier.

http://www.imagination-land.org/posts/2016-01-15-gpaste-3.18.3-released.html

**Comment by Keruspe** [comment]
Seems to be available in the universe repository

http://packages.ubuntu.com/xenial/gnome-shell-extensions-gpaste

**Comment by paulwellnerbou** [comment]
Thanks, @Keruspe,

I have the release tarballs, but ./configure fails as well:

```
./configure: line 15132: syntax error near unexpected token `$VALA_REQUIRED'
./configure: line 15132: `VAPIGEN_CHECK($VALA_REQUIRED)'
```

I installed libvala-dev already.

As Ubuntu 16.04 will be released soon, I will be able to use the xenial package then.

**Comment by Keruspe** [comment]
try installing valac or such?

**Comment by Keruspe** [comment]
I do not use nor know ubuntu and how they split packages.

**Comment by paulwellnerbou** [comment]
valac is installed, but still no success.
