### ISSUE TITLE
Scrolling - or how to see 'hidden' entries?

### ISSUE THREAD

**Issue by motatuc** [Keruspe/GPaste#144]
Hello

Thanks for your work - GPaste is great.
One question though - maybe it got already answered but I could not find anything about it.

So lets say I set display history size to 25 and the max history size to 100.
How can I see those entries that are on the 25th to the 99th place?
I do not see any option like scrolling.

GPaste 3.18.3
Debian sid

Regards
Malu

**Comment by Keruspe** [comment]
Hi,

For now it's indeed not possible from anything else than the command line, apart from using the search feature.

In the gnome-shell extension, scrolling is not really possible if we keep using the nicely integrated widgets provided by gnome-shell. I will try to add some pagination though

**Comment by Keruspe** [comment]
I have some working pagination in the gnome-shell extension locally, might need some polishing and clearly needs to be less ugly, but will definitely be part of GPaste 3.22

**Comment by motatuc** [comment]
Nice, thanks!

Will it be usable with Gnome 3.18 as well? Stucking with Ubuntu stable ;)

**Comment by Keruspe** [comment]
I don't think so, 3.18 is in bugfix-only mode, and so is 3.20 btw. This matches the GNOME release scheme

**Comment by Keruspe** [comment]
So, this is done in the extension now, with some fixes coming to 3.21.91, and it will be ready in the gui for 3.22 too
