### ISSUE TITLE
Manjaro/arch Linux GNOME Shell 3.18.4 with GPaste v3.18.3 it only shows history from primary selection history sync not clipboard

### ISSUE THREAD

**Issue by person666** [Keruspe/GPaste#147]
CTRL-C and CTRL-X both don't make any thing show up in GPaste history. only using the sync primary selection to history option makes anything show up in history and that is just the primary selection. All the appropriate options are on.

PS The tar for 3.18.3 does not build.

**Comment by Keruspe** [comment]
Could you try building GPaste yourself, then start `./bin/clipboard-watcher` in the build directory and see what is printed when you copy stuff ?

By any chance: were you copying from emacs and/or chromium? These two pieces of software are known to do really stupid stuff with clipboard handling at least on X11

**Comment by person666** [comment]
From what commit should I build GPaste for gnome 3.18.4?
The tar and zip for 3.18.3 don't build.

**Comment by Keruspe** [comment]
What is the error you get?

**Comment by person666** [comment]
./autogen.sh returns:
bindings/gi.mk:44: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL
bindings/gi.mk:44: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL
autoreconf: automake failed with exit status: 1

**Comment by Keruspe** [comment]
You don't want to run autogen.sh from a tarball, you directly want to run configure

(it fails here because you are missing devel deps needed o run autogen.sh)

**Comment by person666** [comment]
./configure.ac ?

**Comment by Keruspe** [comment]
./configure

It should be all explained in the README.md

**Comment by person666** [comment]
I read the read me, but zsh: no such file or directory: ./configure.

**Comment by Keruspe** [comment]
Where did you download the tarball from?

**Comment by person666** [comment]
The GitHub releases page over https

**Comment by Keruspe** [comment]
Use the link from the readme please

**Comment by person666** [comment]
I downloaded it, but is there a hash as the file appears to be served over http

**Comment by Keruspe** [comment]
There is now http://www.imagination-land.org/files/gpaste/sha1sum with the sha1sum of all release tarballs.

https should come at some point. Another way to get it is to download it from https://github.com/Keruspe/blog/tree/master/files/gpaste if you trust git better :)

**Comment by person666** [comment]
It installed, but does not work any better then the version in the repo. I restarted the shell and daemon just  to be sure and there is no difference I am using gedit and a variety of other apps to test.

**Comment by person666** [comment]
Is there a unified uninstaller or do I clean it out manually?

**Comment by Keruspe** [comment]
make uninstall should be ok.

I didn't tell you to reinstall it this way though, I told you to run `./bin/clipboard-watcher` from the build directory which is a debug tool.

**Comment by person666** [comment]
Was I supposed to run that before and not install first?

**Comment by person666** [comment]
I just went thru whole the process again, but I can't find ./bin/clipboard-watcher. zsh: no such file or directory: ./bin/clipboard-watcher

**Comment by Keruspe** [comment]
The installation part doesn't matter, it's standalone.

Are you in the directory where you typed "make" when running it? Can you list the contents of the bin repository?

**Comment by person666** [comment]
Yep I amd in the make dir. This is the ./bin tree
bin
├── .dirstamp
├── gpaste
├── gpaste-client
├── gpaste-daemon
├── gpaste-ui
└── .libs
    ├── gpaste-client
    ├── gpaste-daemon
    └── gpaste-ui

**Comment by Keruspe** [comment]
Gah, it probably was added only in 3.20 :-/
