### ISSUE TITLE
Manjaro/Arch gnome 3.20 GPaste not syncing with clipboard.

### ISSUE THREAD

**Issue by person666** [Keruspe/GPaste#148]
I have installed both the latest binary with gnome 3.20.1 and build it from git and it still does not work. ./bin/clipboard-watcher works showing both primary selections and copys/cuts, but the UI does not.

**Comment by Keruspe** [comment]
So clipboard-watcher show the changes from both clipboard and primary but GPaste only tracks primary?

I'll do a release with some debug logging added so we can further debug this

**Comment by person666** [comment]
Yes that is correct.

**Comment by Keruspe** [comment]
I did a 3.18.4 release with some fixes and debug logging added tonight, will do a 3.20.1 within 24h wiwth the same changes so we can debug all this.

**Comment by Keruspe** [comment]
@person666 If you now run `G_MESSAGES_DEBUG=all /usr/libexec/gpaste/gpaste-daemon` (this will require killing the running daemon first), could you paste me the output when it doesn't work?

**Comment by person666** [comment]
@Keruspe I have moved to i3 so I am closing the issue.
