### ISSUE TITLE
Vala version pkg-config issue

### ISSUE THREAD

**Issue by theridane** [Keruspe/GPaste#153]
On systems with no generic (unversioned) valac/vapigen executable, the configure script fails to locate vala at all. For example, I have vapigen-0.32 (`/usr/share/pkgconfig/vapigen-0.32.pc`) but the configure script looks for `/usr/share/pkgconfig/vapigen.pc`. I have no idea how autotools work so I can't provide a patch, but [here's a cmake implementation](https://github.com/rcrowther/Vala_CMake/blob/master/vala/FindVala.cmake) for reference.

**Comment by Keruspe** [comment]
Can you provide some logs please?

Out of curiosity, which distribution is this? Usually there's a switch to select the default vala version.

Quick fix is to re run the autotools (launch autogen.sh), or you can probably submit a fix for that directly to vala upstream as I use only the autotools macro provided by upstream, so it's definitely not a GPaste issue.

**Comment by theridane** [comment]
[config.log](https://gist.github.com/theridane/dc386d0d4226a565c539204ecc5419a8)

It's Gentoo. There is no default valac/vapigen like in e.g. Ubuntu because the upstream doesn't specify one, and it rarely makes sense to depend on an unspecified version of Vala since it changes so fast (that's the rationale given by Gentoo brass in various bug reports).

I've done some research and it's looking like there really is an issue with either the way Gentoo approaches this or the upstream macros. Official GNOME apps written in Vala are all distributed with the C sources already generated, so `valac` is never actually called on the compiling machine.

**Comment by Keruspe** [comment]
Vala was indeed changing really fast at its beginning but there has been no breakage i at least 3 or 4 years now.

GPaste doesn't even have a single vala source file, I only use vapigen to generate a vapi file to use in vala projects which would want to use GPaste library.

It's strange that gentoo doesn't have a "eclectic vala" module.

You can try to run ./configure VAPIGEN=vapigen-0.32 or you can try with --disable-vala maybe

**Comment by theridane** [comment]
I'll close this as it obviously has nothing to do with GPaste, we'll figure it out in Gentoo or GNOME channels :)
