### ISSUE TITLE
[enhancement] missing icon

### ISSUE THREAD

**Issue by mattia-b89** [Keruspe/GPaste#154]
in a strange way, GPaste application misses the icon, the one in the top-left window corner

this is a screenshot:
http://i.imgur.com/7ah3GAL.png

and you can see that info dialog has icon as well the gnome applet

**Comment by Keruspe** [comment]
Which icon do you expect seeing there?

Also, which version of gtk+ do you have installed?

**Comment by mattia-b89** [comment]
I expect to see a littler version of the icon used in the `about` dialog
(in foreground on my screenshot);
e.g. here with the standalone system monitor app for the gnome DE:
http://i.imgur.com/4gTdrrs.png

I'm on Arch Linux x86_64 with gnome 3.20.2, gtk3-3.20.5-2

**Comment by Keruspe** [comment]
Oh, right, I don't actually have that part displayed here, and I didn't know it was customisable.

Should be fixed by 323f08d2a30eb361255f3c6f6400e06d3c469985

I might release GPaste 3.20.2 tomorrow or so, please reopen if it's still not fixed in this version

**Comment by mattia-b89** [comment]
thanks, FIXED!
