### ISSUE TITLE
[enhancement] option menu graphical issues

### ISSUE THREAD

**Issue by mattia-b89** [Keruspe/GPaste#157]
as you can see from the screenshot
http://i.imgur.com/JpbpHVA.png

the last item has text cut out

another thing involve buttons that act as tab: at the moment these buttons can be confused with main program button due to the same background colour of the main app and the option menu, and because there is no space from the top border of the option menu

**Comment by Keruspe** [comment]
The first issue seems like a gtk+ issue to be.

In fact, both issues are due to the fact that the window is really tiny, when the window it big enough, the menu goes underneath. But I'll sure add some margin there

**Comment by Keruspe** [comment]
@mattia-b89 Are these issues still present with gtk+ 3.22 and GPaste 3.21.91?

**Comment by mattia-b89** [comment]
@Keruspe Actually I am still at 3.20 and with no more this issue.
When I upgrade to .22 I'll update my report...

sent from my E2

**Comment by Keruspe** [comment]
Oh, so this is even fixed for 3.20 now? Might be some combination of internal gtk+ fix + my margin stuff.
Closing then, feel free to reopen if the issue reappears someday.

**Comment by mattia-b89** [comment]
nono!!!
sorry, I misunderstand ... this issue is still present with 3.20

anyhow, I will update the status when I will upgrade my system

**Comment by mattia-b89** [comment]
solved! http://imgur.com/a/rTs6E
at least the "cut" item
in fact, in order to get a better view you can add a little bit of space above the tabs (always in the menu...)

**Comment by mattia-b89** [comment]
the issue has come back

**Comment by Keruspe** [comment]
What is the problem now?

**Comment by mattia-b89** [comment]
Exactly the same: in the menu, last item is cut out. I don't know exactly
starting when it is appeared

powered by CM
