### ISSUE TITLE
gpaste 3.20.1 messes up soname versioning

### ISSUE THREAD

**Issue by DimStar77** [Keruspe/GPaste#158]
The relase gpaste 3.20.1 messed up the library soname.

in 3.20.0 it was libgpaste.so.6, in 3.20.1 it was lowered to libgpaste.so.5

The issue comes from configure.ac (see commit d9ccd33)
 -m4_define([gpaste_lt_version],   [6:0:0])
+m4_define([gpaste_lt_version],   [6:1:1])

That must have been a really bad mistake - there is no way you meant to do that - if the description above makes any sense, A is never increased together with C. In fact, this resulted in the library being called libgpaste.so.5 again, after it was already libgpaste.so.6 in the past...

**Comment by Keruspe** [comment]
Heh, indeed, my mistake.
Actually the real problem is that I mistakenly bumped from 4 to 6 in the first place, not sure why I thought bumping the last one made sense. Will fix that in next release

**Comment by DimStar77** [comment]
Mistakes can happen - the next release probably should ensure that a soname is used that could not have floated around yet and that future versions won't collide accidentally
