### ISSUE TITLE
[enhancement] high resolution icon

### ISSUE THREAD

**Issue by mattia-b89** [Keruspe/GPaste#159]
hi, as you can see from this screenshot  http://i.imgur.com/jkWp4Kx.jpg
program icon are "blurry" I think due to low resolution icon used

PS: I know, this is a merely cosmetic "issue" but even this kind of "issue" are important to achieve best results!

**Comment by Keruspe** [comment]
Hi,
GPaste doesn't actually ship any icon, it uses the icon from your icon theme (by default, the one provided by gtk+), so you should ask your icon theme for that

**Comment by mattia-b89** [comment]
oh.... this is the reason why I haven't find it!
