### ISSUE TITLE
Add function to remove formatting from string  

### ISSUE THREAD

**Issue by gunwald** [Keruspe/GPaste#160]
It would be very handy to have a functions, that removes all formatting from a string. I mean, if you copy a text out of a program like LibreOffice it usually comes with all formatting like italic, links etc. To convert this text to a plain string you have to paste it to a text editor an copy it again. This can be very annoying. 
GPaste could provide this functionality. I would suggest to use middle mouse click to an entry in the history to trigger it.
Other clipboard tool (for example in CairoDock) are providing this function as well.

**Comment by Keruspe** [comment]
What transformation would be needed?
Is there any library to do that?

**Comment by gunwald** [comment]
Unfortunately I don't know nothing about the clipboard and how it is managed in Linux/GNOME. But I suppose there is a standard format in which all formatting is converted by coping it to the clipboard. If we find out what format it is, it would be easy to strip it. But I am afraid I am not much of a help here.

**Comment by Keruspe** [comment]
Note that this has nothing to do with the clipboard, you just want to transform a string into another string at this point.
I have never used libreoffice and I don't plan to, ever, so unless someone provides me with the data that needs to be stripped, and maybe a library to do the transformation, I'm afraid it's not gonna happen.
I have absolutely no knowledge as to how libreoffice handles formatting, I never use formatted text.

Wrt standard for the clipboard handling, the standard is to just get whet you're given without altering the data, which is what GPaste does right here.

Can you provide an example of what you get VS what you'd want to get when you paste a formatted string?

**Comment by Keruspe** [comment]
Closing as this doesn't seem to go anywhere.
Please reopen if you get more data some day.
