### ISSUE TITLE
3.20.4, 3.18.5 git tags missing

### ISSUE THREAD

**Issue by lkraav** [Keruspe/GPaste#162]
Hi. I'd like to update https://github.com/gentoo/gentoo/ ebuilds. Posted on your [blog Disqus](http://www.imagination-land.org/posts/2016-06-28-gpaste-3.20.4-released.html#comment-2757418004) but no response. Trying again here.

**Comment by Keruspe** [comment]
Heh, I usually don't forget those, thanks!
(It seems I no longer get email notifications from disqus :/)
