### ISSUE TITLE
downstream gpaste-daemon: random crash (SIGABRT)

### ISSUE THREAD

**Issue by kapouer** [Keruspe/GPaste#163]
Hi,

please see https://bugs.debian.org/832313
It seems the version used here is not the latest (though the latest 3.20.4 is available in debian),
but i'm not sure it's related to the fix in 3.20.4.

**Comment by Keruspe** [comment]
The only mention to gpaste I see in this stacktrace is the entry point... Looks like an internal gtk error I'd say, unless I'm missing something.

**Comment by Keruspe** [comment]
I believe it's either not a GPaste bug, or it was fixed in 3.20.x already as it seems to ring a bell, thinking back about it.

Please reopen if it happens again with an up to date verson of GPaste

**Comment by kapouer** [comment]
Hello again,
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832313#14
has a backtrace on a "near release" debian/stretch.

**Comment by Keruspe** [comment]
I still think it's an internal gtk error.
Folowing the whole stack, it seems to happen between the reception of the X11 event by gtk and the moment when gtk forward us an event.
Maybe you want to report a bug to upstream gtk?
