### ISSUE TITLE
Error running configure

### ISSUE THREAD

**Issue by melarish** [Keruspe/GPaste#164]
configure.ac:65: installing 'build-aux/missing'
src/gi.mk:29: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL
Makefile.am:65:   'src/gi.mk' included from here
src/vapi.mk:32: error: ENABLE_VAPIGEN does not appear in AM_CONDITIONAL
Makefile.am:66:   'src/vapi.mk' included from here
Makefile.am:51: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:51:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:51:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:51:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:51:   its definition is in aclocal's search path.
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
autoreconf: automake failed with exit status: 1
m@m:~/Downloads/GPaste-master$ ./configure --sysconfdir=/etc
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for ar... ar
checking the archiver (ar) interface... ar
./configure: line 3958: syntax error near unexpected token `2.2.6'
./configure: line 3958: `LT_PREREQ(2.2.6)'
m@m:~/Downloads/GPaste-master$ make
make: *** No targets specified and no makefile found. Stop.

**Comment by Keruspe** [comment]
Why are you trying to build from git?
You need several devel dependencies in order to do that, and the dependencies are not the same for every distribution.

**Comment by melarish** [comment]
Because it says "Steps to install it after cloning" so I thought that's what you were supposed to do :) Anyway I tried the tarball too and it got stuck behind GTK not installing, so I'll come back to this once that gets sorted!
