### ISSUE TITLE
copy/past via mouse wheel

### ISSUE THREAD

**Issue by Cherkah** [Keruspe/GPaste#165]
hi, first great job and  good feedback..

2 issues:
A) i can copy some text by shortcuts (ctrl + c), right click or mouse-wheel (activated) but it seems  that gpaste do not recognize copy by mouse-wheel.
 to reproduce it:
just select text via mouse-weel and looking for the text in gpaste GUI

B) about sweep's icon
 brush icon appear in GUI but don't in the float extension (see picture bellow)
![capture d ecran de 2016-08-10 18-35-36](https://cloud.githubusercontent.com/assets/16431970/17573693/175b897e-5f2a-11e6-809b-e84e0ef9640a.png)

**Comment by Keruspe** [comment]
Hi,

A) You can enable that in the setting. "Primary selection affects history"

B) I'm not sure to follow here. Maybe what you're looking for is in the right-click menu on the history name at the left?

**Comment by Keruspe** [comment]
Please reopen the issue if that wasn't hat you were looking for
