### ISSUE TITLE
release 3.21.9x ?

### ISSUE THREAD

**Issue by kapouer** [Keruspe/GPaste#166]
Hi,
debian/sid has gnome 3.21.90, so it would be a good occasion for testing gpaste !

**Comment by Keruspe** [comment]
Hi,
I'd like to do one, but I need to finish some stuff prior to that and didn't manage to find enough time lately.
Hopefully this week end

**Comment by kapouer** [comment]
Ok, thanks. Meanwhile i've installed your master branch and it seems to be all right for now.

**Comment by Keruspe** [comment]
Now I just want the current page to be highlighted in the page switcher, and the number of pages updated when needed, and I'm doing a release

**Comment by Keruspe** [comment]
3.21.90 released.
3.22 will be late but there will probably be another 3.21.9x release before that.

**Comment by kapouer** [comment]
Cool, building and uploading to debian...
