### ISSUE TITLE
accessibility a bit less cool with pagination

### ISSUE THREAD

**Issue by kapouer** [Keruspe/GPaste#167]
Hi,
i'm a big user of gnome-paste, typically using only keyboard shortcuts:
- alt-space to open the menu
- down arrow and enter to select
- then ctrl-v

It's very cool and fast once one is used to it.
In [latest](https://github.com/Keruspe/GPaste/commit/d871d9d48e8f71aae0524a1946b68225990e669f) version however, the pagination menu is a bit in the way and adds an extra keystroke.

**Comment by Keruspe** [comment]
That's one of the things I want to polish before rolling a 3.21.9x release yup.
Ideally, up and down will just work as before, bypassing the page switcher, and left and right will go to previous/next page without changing the selected index I think

**Comment by Keruspe** [comment]
Should be better now
