### ISSUE TITLE
Shortcut or configuration option to open applet only?

### ISSUE THREAD

**Issue by tohuwabohu** [Keruspe/GPaste#183]
I enjoy using gpaste on a daily basis since a very long time. I can't imagine what I would do without it, makes everything so much easier, great job!

But after switching from Ubuntu to Arch Linux I'm struggling the find my way back into my old workflow. The problem is that when using the *Display the history* shortcut **both UIs** - the regular one and the applet - **are activated**. This is kind of overkill and even more anoying as the ui can't be dismissed easily (it's fixed now, I've seen that).

So, is it possible to bind a shortcut in a way to open the applet only and not the ui at the same time? For instance using `gpaste-client show-history` first opens the applet and right after that the ui. But I'd like to use the applet only. Is there a configuration option or a magic switch?

I'm using gpaste 3.22.1-1 on Arch Linux.

**Comment by lkraav** [comment]
I also found this weird and confusing, because the shell extension has no visible instruction on "don't activate this when...". So I turned the extension off and assigned a shortcut key to launch the main UI.

**Comment by Keruspe** [comment]
Hmm, that's weird indeed.
Do you use gnome-shell? If yes, why do you have gpaste-applet installed?

**Comment by tohuwabohu** [comment]
I have the gnome-shell installed. Why the applet? The applet does exactly what I need: shows me the most recent entries, allows me to search and remove entries and can be completely controlled from keyboard. That's all I need. I'm actually surprise to see the regular gpaste ui, I don't recall having seen it on Ubuntu 16.04.

So you reckon I should just drop the applet and use the normal ui?

**Comment by Keruspe** [comment]
What you're describing here is the gnome-shell extension, not the applet.
The applet (process name "gpaste-applet") is only a legacy statusbar icon that pops up the "normal" ui.

**Comment by tohuwabohu** [comment]
Ahhh, ok. So in that case the issue summary would be ...

> Shortcut or configuration option to open gnome-shell extension only

Sorry about the confusion with the applet.

Weird enough, I've tried it again and now it works as expected: 'Display the history' is bound to a shortcut and only the shell extension shows up. Can't explain that.

**Comment by Keruspe** [comment]
When the applet is launched, "Display the history" makes it spawn the "normal" ui

**Comment by Keruspe** [comment]
legacy applet will be removed in next version, so this issue will disappear altogether

**Comment by tohuwabohu** [comment]
Great, thank you very much.
