### ISSUE TITLE
gpaste-daemon spams log

### ISSUE THREAD

**Issue by mattia-b89** [Keruspe/GPaste#186]
I get these errors http://pastebin.com/Dt2E6Zbz when I copy a huge amount of data, let's says 9600 lines of 80 characters

Steps to reproduce it:
* open gedit
* insert 9600 lines of 80 'x' characters NB: could be needed less data but I don't know exactly...
* select them all, copy
* systemd journal will report the abovementioned errors

**Comment by Keruspe** [comment]
Hi,

Any chance you can get a gdb backtrace for this? (with coredumpctl gdb maybe)

**Comment by mattia-b89** [comment]
do you mean this http://pastebin.com/UjzEgjYH ?

**Comment by Keruspe** [comment]
I just tried replicating exactly the same as you and get no error on my side. Pasted the copied text in another file and the diff was empty, so everything went fine

**Comment by mattia-b89** [comment]
when I encountered the issue I was on GTK3 3.22.4

now, me too, I can't no more reproduce the bug... maybe the problem was GTK since now (with 3.22.5) the issue has gone
