### ISSUE TITLE
Prompt before clearing history

### ISSUE THREAD

**Issue by blackjackshellac** [Keruspe/GPaste#187]
I just accidentally wiped my clipboard history because I didn't grok the "brush" symbolic icon. It would be nice if there were a "Do you want to clear clipboard history?" dialog, similar to the one that asks if you want to delete the clipboard history.

**Comment by Keruspe** [comment]
Hi, you're speaking of the button in the gnome-shell extension right?
There's already a prompt when done from the main ui. Will add one for the extension too
