### ISSUE TITLE
Elementary OS?

### ISSUE THREAD

**Issue by ylluminate** [Keruspe/GPaste#191]
Any tips or steps on installing this properly on Elementary OS?

**Comment by Keruspe** [comment]
I think GPaste is packaged for ubuntu, and iirc elementary is based on ubuntu, so using the ubuntu package might work I guess. Not really familiar with deb distros though.

**Comment by ylluminate** [comment]
Well, it appears that there is an older ppa, but I'm not seeing anything recent..... That's where I'm running into a wall. I was about to compile it myself, but then saw some missing pkgs there as well for support so I thought I'd check to see if there was already a more standard method for installation first.

FYI, I threw up a question here: https://elementaryos.stackexchange.com/questions/10537/how-to-install-gpaste

If, at the end of the day, I have to compile it, what are the primary packages that I need in place for compilation on an ubuntu distro?

**Comment by Keruspe** [comment]
It's not a PPA anymore, it's an official package: https://launchpad.net/ubuntu/+source/gpaste

**Comment by Keruspe** [comment]
At some point the needed packages where listed there: https://github.com/Keruspe/GPaste/blob/gpaste-3.18/README.ubuntu

**Comment by ylluminate** [comment]
That's really interesting. `apt-cache search gpaste` isn't yielding anything on elementary... I had tried that first off thinking it would be there.  HMMmmm.
