### ISSUE TITLE
No system tray icon

### ISSUE THREAD

**Issue by Vistaus** [Keruspe/GPaste#192]
I've just compiled GPaste succesfully on Solus (after manually upgrading Automake to 1.15) but the icon in the system tray is not shown. Using Solus Budgie.

How to solve this?

**Comment by Keruspe** [comment]
If you want a legacy tray icon, you'll need to use a GPaste 3.22 release.
Starting with 3.24 (and it current git) the tray icon has been removed as it's deprecated. The only thing it did was to launch the graphical interface that you can already launch using keyboard shortcuts or as any other application, and the whole concept behind the tray icon is deprecated in last gtk3 versions and is totally gone in gtk4.
What do you need the tray icon for?

**Comment by Vistaus** [comment]
Sorry, forgot to mention that I did download and install GPaste 3.22.1

What do I need the icon for? Well, I want to be able to quickly select something else from the menu using the mouse, just like, say, ClipIt, Klipper, etc. provide.

**Comment by Keruspe** [comment]
You need to pass --enable-applet to configure in ordre to get the tray icon. But it won't provide you with a menu by itself. Clicking on it will have the same effect as running `gpaste-client ui`

**Comment by Vistaus** [comment]
Oh, well that sucks. GPaste seems to be the only modern clipboard manager for Linux with an easy interface. But it's useless for me without a quick menu. Thanks anyway...

**Comment by Keruspe** [comment]
Did you actually try the graphical interface I'm speaking of? I'm pretty sure it does exactly what you want from a "quick menu".

The fact that it's "modern" is actually the cause for not having a tray icon, as it's something that won't work with futures versions of gnome/gtk on Xorg, and already doesn't work when using wayland.

**Comment by Vistaus** [comment]
I've tried the GUI but it's not as convenient IMHO. Selecting something from a tray menu is much faster and easier on the eyes.

So it seems like you're only targeting GNOME, rather than GTK-based distributions who still use a system tray like Solus... alright then.

**Comment by Keruspe** [comment]
Well, the gnome-shell extension (which is basically a modern and more flexible try icon) is targetting only GNOME, yes.

The graphical interface though isn't. It actually evolves mostly to follow requests made from people using other desktop environments like i3, xmonad or others. If you have any suggestion to make it more convenient, I'm be happy to hear those :)

Fwiw, when I say that the mechanism behind the tray icons is deprectaed in gtk3 and gone in gtk4, I'm not speaking only for gnome, it's really inside of gtk itself so it will affect all gtk-based distributions: it was deprecated 2 years and a half ago: https://git.gnome.org/browse/gtk+/commit/gtk/deprecated/gtkstatusicon.h?h=gtk-3-22&id=cab7dcde1bef1ea589a9f3c4d8512e59ade8a4a2 and removed last october https://git.gnome.org/browse/gtk+/commit/gtk/deprecated/gtkstatusicon.h?id=d2a8667f835ddce4ac88b9bee143556f9efa93c4

I have to admit though that it's more keyboard-centric than mouse-centric wrt spawning. If you're into keyboard, I like to beleive that `<Ctrl><Alt>G` then typing `foo` then `Enter` to select the last thing you copied containing foo, for example, is quite handy.

**Comment by Vistaus** [comment]
If it's removed, then how come the system tray still works in Solus? Solus is using an *unpatched* version of GTK 3.22.x ...

**Comment by Keruspe** [comment]
It's deprecated since 3.14 and removed in 3.89 which is development version
for gtk4, sorry if I was unclear

**Comment by Vistaus** [comment]
Yeah, I get that now. Too bad :disappointed:

**Comment by IvanMalison** [comment]
> Fwiw, when I say that the mechanism behind the tray icons is deprectaed in gtk3 and gone in gtk4, I'm not speaking only for gnome, it's really inside of gtk itself so it will affect all gtk-based distributions: it was deprecated 2 years and a half ago: https://git.gnome.org/browse/gtk+/commit/?h=gtk-3-22&id=cab7dcde1bef1ea589a9f3c4d8512e59ade8a4a2 and removed last october https://git.gnome.org/browse/gtk+/commit/?id=d2a8667f835ddce4ac88b9bee143556f9efa93c4

That is just XEMBED. Are you aware of StatusNotifierItem? Which is a newer, Display server agnostic protocol that can be used to support tray icons?

**Comment by Rik44444** [comment]
hi, 
just to note I'm also missing a tray icon! Just installed this as a replacement for copyq that stopped working in Ubuntu 23.04, but I loved the tray icon of copyq, so i think i'll try Klipper if Gpaste does not offer a tray icon
Rik

**Comment by alkaris2** [comment]
> What do you need the tray icon for?

Hmm... oh I dunno.... maybe to access the stuff you've copied into your clipboard that GPaste has from the tray? Y'know cuz you can't see whats been saved by GPaste any other way. Especially when it's remembering a bunch of other stuff you've copied into your clipboard that kind of thing. There are alternatives to displaying tray icons from apps like these even if they've been `depreciated` in GTK4 entirely, I'm just baffled why you haven't looked at this more. `AppIndicator` and `KStatusNotifierItem` as optional dependencies, or just using whatevers been installed, only 2 lines of code to check which ones are installed when compiling or installing from precompiles ie; AppImages etc...
