### ISSUE TITLE
autoreconf: command not found

### ISSUE THREAD

**Issue by elcega** [Keruspe/GPaste#193]
Error trying t install pandaseq, 
it does not let me run ./autogen.sh 

USER:pandaseq user$ ./autogen.sh
./autogen.sh: line 5: autoreconf: command not found

**Comment by Keruspe** [comment]
In ordre to build from git, you need a standard build environment with autotools, make, a compiler and development libraries.
Package names depend on your distribution.

**Comment by Keruspe** [comment]
Btw, if you build from a release tarball you won't need to run autogen.sh

**Comment by elcega** [comment]
I downloaded the package from a tarball, but I can't install pandaseq and tried to do it differently.
Pandas command is not found, meaning I haven't install it yet. What is the best way to install it? I am using a new Mac and I have been installing Xcode, MacPorts, Fink, Brew to try different options and still can't.
What do you recommend me?

Thanks

**Comment by Keruspe** [comment]
Hrrm, wait. I didn't realize that in your first message, but you're actually speaking of pandaseq?
How did you get there then? This project has nothing to do with pandaseq

**Comment by elcega** [comment]
Following steps from here 
http://hpc.ilri.cgiar.org/pandaseq-software

But already did it with Brew. Thanks and sorry
