### ISSUE TITLE
GPaste doesn't work with WPS Office

### ISSUE THREAD

**Issue by Vistaus** [Keruspe/GPaste#194]
When I try to copy something WPS Office, GPaste doesn't track the changes. GPaste works fine in other apps and ClipIt (which I used prior to GPaste) worked fine with WPS Office.
Using GPaste 3.22.1 on Solus (Budgie).

How to solve this?

**Comment by Keruspe** [comment]
Can you run the gpaste-daemon from a terminal with debug logging on?

Should be something like `G_MESSAGES_DEBUG=all /usr/libexec/gpaste/gpaste-daemon` depending on where your distribution installs it. You'll have to kill the running daemon before.

Try to see if the daemon logs something or not where you try to copy things in WPS Office. I tried to reproduce with a fresh download but it seems to work fine here.

**Comment by Vistaus** [comment]
I don't think it logs something, but here's the output anyway:

`[14:31:02]` vistaus@vistaus-solus /home/vistaus/Downloads (127) 
> env G_MESSAGES_DEBUG=all /usr/libexec/gpaste/gpaste-daemon

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:150:54: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:172:56: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:177:74: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:181:56: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:186:58: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:194:56: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:199:58: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:207:56: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:212:58: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:223:74: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:230:64: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:233:75: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:1052:69: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:1081:74: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:1092:74: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:1095:58: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:1102:74: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:1105:58: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:1332:71: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:1339:62: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:1343:74: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:1464:62: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:1468:58: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:1471:56: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:1865:9: Not using units is deprecated. Assuming 'px'.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:1865:9: Expected a string.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:2663:53: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:2693:51: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:2696:59: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:2701:53: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:2701:87: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:2946:8: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:2946:17: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3218:54: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3531:71: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3538:62: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3541:74: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3549:52: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3621:60: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3629:67: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3633:54: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3644:60: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3837:8: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3837:20: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3857:54: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3868:8: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3868:22: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3871:8: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3871:28: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3874:8: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3874:22: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3891:12: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3891:12: Expected a string.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3897:14: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3897:14: Expected a string.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3903:16: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3903:16: Expected a string.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3908:14: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3908:14: Expected a string.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3975:12: Expected a string.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3977:16: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:3977:16: Expected a string.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:4023:12: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:4023:12: Expected a string.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:4026:66: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:4202:72: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:4209:62: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk.css:4212:73: Using one color stop with linear-gradient() is deprecated.
(gpaste-daemon:27027): Gtk-DEBUG: Connecting to session manager

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:211:56: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:216:58: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:224:56: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:229:58: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:237:56: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:242:58: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:253:74: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:260:64: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:263:75: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1096:69: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1126:74: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1137:74: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1140:58: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1147:74: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1150:58: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1382:71: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1389:62: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1393:74: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1514:62: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1518:58: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1521:56: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1920:9: Not using units is deprecated. Assuming 'px'.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1920:9: Expected a string.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:2439:33: '-gtk-gradient' is not a valid color name

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:2725:53: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:2755:51: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:2758:59: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:2763:53: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:2763:87: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3008:8: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3008:17: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3281:54: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3597:71: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3604:62: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3607:74: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3615:52: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3687:60: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3695:67: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3699:54: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3710:60: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3903:8: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3903:20: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3923:35: 'linear-gradient' is not a valid color name

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3934:8: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3934:22: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3937:8: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3937:28: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3940:8: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3940:22: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3957:12: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3957:12: Expected a string.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3963:14: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3963:14: Expected a string.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3969:16: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3969:16: Expected a string.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3974:14: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3974:14: Expected a string.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:4041:12: Expected a string.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:4043:16: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:4043:16: Expected a string.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:4089:12: not a number

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:4089:12: Expected a string.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:4092:66: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:4270:72: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:4277:62: Using one color stop with linear-gradient() is deprecated.

(gpaste-daemon:27027): Gtk-WARNING **: Theme parsing error: gtk-dark.css:4280:73: Using one color stop with linear-gradient() is deprecated.
(gpaste-daemon:27027): GPaste-DEBUG: history: elect biggest
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: set text
(gpaste-daemon:27027): GPaste-DEBUG: item: set state: 1
(gpaste-daemon:27027): GPaste-DEBUG: history: selected
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: select
(gpaste-daemon:27027): GPaste-DEBUG: PRIMARY: select item
(gpaste-daemon:27027): GPaste-DEBUG: PRIMARY: select text
(gpaste-daemon:27027): GPaste-DEBUG: PRIMARY: set text
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: select item
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: select text
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: set text
(gpaste-daemon:27027): GPaste-DEBUG: history: elect biggest
(gpaste-daemon:27027): GPaste-DEBUG: PRIMARY: set text
(gpaste-daemon:27027): GPaste-DEBUG: PRIMARY: owner change
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: targets ready
(gpaste-daemon:27027): GPaste-DEBUG: PRIMARY: set text
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: text ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify finish
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: owner change
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: targets ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: text ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify finish
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: owner change
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: targets ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: no target ready
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: clear
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: select item
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: select text
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: set text
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: owner change
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: targets ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: text ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify finish
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: owner change
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: targets ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: text ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify finish
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: owner change
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: targets ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: no target ready
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: clear
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: select item
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: select text
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: set text
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: owner change
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: targets ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: text ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify finish
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: owner change
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: targets ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: text ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify finish
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: owner change
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: targets ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: no target ready
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: clear
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: select item
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: select text
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: set text
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: owner change
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: targets ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: text ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify finish
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: owner change
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: targets ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: text ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify finish
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: owner change
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: targets ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: no target ready
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: clear
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: select item
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: select text
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: set text
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: owner change
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: targets ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: text ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify finish
(gpaste-daemon:27027): GPaste-DEBUG: CLIPBOARD: owner change
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: targets ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: text ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify finish
(gpaste-daemon:27027): GPaste-DEBUG: PRIMARY: owner change
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: targets ready
(gpaste-daemon:27027): GPaste-DEBUG: PRIMARY: set text
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: text ready
(gpaste-daemon:27027): GPaste-DEBUG: clipboards-manager: notify finish`

**Comment by Keruspe** [comment]
Hum, that's really weird, the "owner change" event which tells that something has been copied is correctly received but the the result is not added to the history.

**Comment by Keruspe** [comment]
That usually happens when what you're selecting is what you already have in your clipboard

**Comment by Vistaus** [comment]
But what I copied wasn't in the clipboard yet. I opened a totally new document where I put some random text and copied that.

**Comment by Keruspe** [comment]
The "clipboards-manager: no target ready" is probably the culprit, but then the problem wouldn't really be on the GPaste side.

I guess the clipboard managers you're speaing of are only capable of handling text, right? So they directly ask WPS for the text that has been copied, that's why they work I guess.
GPaste also supports copying files and images, so it starts by asking "what kind of stuff did you just copy? was it some text, some image, anyting else?" and that logs tells us that we got an empty answer.

The specifications of clipboards tell that the software shouldn't answer with an empty list if anything is copied, so that would be a bug on the other side, if that's the issue (I might be wrong about it, of course).
We could try to ask for text as a fallback, I guess, as a workaround for that kind of situations.

**Comment by Vistaus** [comment]
Yes, ClipIt only supports text AFAIK. I could test your latest commit but then I'd lose the applet. Choices, choices... :confused:

**Comment by Keruspe** [comment]
I'll probably dorp that in another repo when i'll release 3.24: https://gist.github.com/Keruspe/f6d02fa8027aceb7f062ca9a95f2daa8
Should be more or less the same that the status icon in 3.22. This way GPaste stands legacy-free and people still can use that

**Comment by Vistaus** [comment]
That'd be sweet :smile: 

Anyway: I've just tested the gpaste-3.22 branch with your latest commit and now it works in WPS Office. Although I do have to hit Ctrl+C twice before it actually copies it from WPS. But at least it's working and that's the most important to me :smile:

**Comment by Keruspe** [comment]
Cool, I'll do some 3.22 release soon-ish then
