### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by Vistaus** [Keruspe/GPaste#196]
I know you haven't set up GPaste on Transifex or Weblate yet but as a freelance translator, I just couldn't resist translating it anyway, so here you go :) (po is from latest git master)

https://file.io/uO19pr
(had to upload elsewhere as GitHub doesn't let me upload po files)

**Comment by Keruspe** [comment]
Hi,

Thanks a lot. A can't seem to be able to download it though.
Can you maybe make a pull request?

(GPaste is not on transifex because as far as I understood there is no free plan and I don't get any profit from GPaste)

**Comment by Vistaus** [comment]
Hmm, I thought there was a free plan on Transifex but I could be wrong though as I'm only a translator so I never upload anything to it :P A totally free option is Hosted Weblate: http://hosted.weblate.org

Strange that you can't download it. I'll try to make a pull request but I've never created a pull request so I hope I'll be able to it.

**Comment by Keruspe** [comment]
Or you can maybe do a gist?

**Comment by Keruspe** [comment]
@Vistaus Alternatively, you still can send it by email. It would be sad to lose your work

**Comment by Vistaus** [comment]
@Keruspe I'm so sorry, I totally forgot this issue! I've now uploaded it as a gist (thanks for the suggestion btw! :smiley: )
https://gist.github.com/Vistaus/d831c22893b59f4e2d2ef6616af5a606

**Comment by Keruspe** [comment]
Thanks!

**Comment by Vistaus** [comment]
You're welcome! :smile_cat:
