### ISSUE TITLE
Make compatibile with mutter 3.24

### ISSUE THREAD

**Issue by jbicha** [Keruspe/GPaste#197]
mutter changed its [library naming](https://git.gnome.org/browse/mutter/commit/?id=4ebc55f2) in 3.23.90 so the configure.ac check will have to be updated.

```
-    PKG_CHECK_MODULES(JS_EXTENSION, [mutter-clutter-1.0])
+    PKG_CHECK_MODULES(JS_EXTENSION, [mutter-clutter-0])
```

But when I did a quick search of your code, I didn't see any places where mutter was specifically being used so maybe this check isn't necessary?

**Comment by Keruspe** [comment]
It's used in the javascript files.

It's in my todo list but I have some packaging to do first in order to test
that.

**Comment by jbicha** [comment]
If you just need a GNOME 3.23.90 platform to test with, Ubuntu GNOME 17.04 (almost Beta 1) has that:
http://cdimage.ubuntu.com/ubuntu-gnome/daily-live/current/

Other distros may have 3.23.90 too (or will soon).

**Comment by Keruspe** [comment]
I don't use ubuntu and I'm the gnome packager for the distro I use ;)

**Comment by jbicha** [comment]
I didn't know that. Great!

Packaging gnome-shell this time is more work because of mozjs38 but you probably already knew that.

**Comment by Keruspe** [comment]
It's now fine in master.
Hopefully in a preview release soon
