### ISSUE TITLE
Track changes toggle in Gnome extension doesn't work

### ISSUE THREAD

**Issue by FMuro** [Keruspe/GPaste#198]
Track changes is activated on startup. When I click on the track changes toggle in the Gnome extension, it apparently changes state, but it really doesn't. This can be easily checked by copying and pasting and also by opening the main gui. If I try to toggle it again, nothing happens, it stays appartently off but working. The only way to make it look on is opening the main gui and toggling off and then on therein (this does work). I'm using version 3.22.1 from Fedora 25 repos.

**Comment by Keruspe** [comment]
Hi,

Thanks for the report, I can indeed reproduce, I'll fix that asap

**Comment by Keruspe** [comment]
Should be fixed now, I'll do a bugfix release within a week I guess to see if I find anything else before that.
(I think I have a couple related to pagination)

**Comment by FMuro** [comment]
Keruspe, thanks a lot! Forgot to say how awsome this piece of software is. I couldn't live without it, at least in Gnome.
