### ISSUE TITLE
Can't search after I moved in history items

### ISSUE THREAD

**Issue by BlackYoup** [Keruspe/GPaste#200]
How to reproduce: Open the GUI and navigate through history items. Then, try to type some letters / numbers to search for a given history item. The search doesn't appear, you have to close the GUI and re-open it to search.

My use case here is that I thought I had an history entry in the 5th position, quickly pressed the arrow keys to "scroll" but then realized that wasn't the good entry. Then, I tried to search by keyword

**Comment by Keruspe** [comment]
It actually used to be a feature, as I only forwarded keystrokes to the search entry when it has the focus, but it makes sense to always grab unknown keys there
