### ISSUE TITLE
gpaste-client help: gpaste-client refuses to add text to clipboard with some special characters

### ISSUE THREAD

**Issue by stefancocora** [Keruspe/GPaste#202]
Thank you for spending your time to maintain this piece of software !

I've hit a issue with adding text to the gpaste clipboard manager using gpaste-client. Some text works , but other pieces of text don't work.

Do you know of a way to make this work ?
Is it a bug in the `gnome-client` text validation ?

---

**Three test cases one with tmux copy buffer, two without**

**1) plain echo, without tmux copy buffer**
**How to reproduce**
- echo some text with some special characters ( similar chars as the gpaste-client help page ) and pipe it to gpaste-client to add to clipboard
```
echo "atsrarst <astar>: arstraart" | gpaste-client add
```

**What was expected**
- I expected to see this line of text added to the gpaste gnome shell extension

**What actually happened**
- gpaste client treated that piece of text as invalid and showed the gpaste-client help https://github.com/Keruspe/GPaste/blob/master/src/client/gpaste-client.c#L147

---

**2) just gpaste-client**
**How to reproduce**
- try to add some text to the gpaste clipboard manage with gpaste-client. Tried both with zsh and bash
```
gpaste-client add --separator <string>: add the given separator between each item when merging  
zsh: no such file or directory: string
...
gpaste-client add --separator <string>: add the given separator between each item when merging
bash: string: No such file or directory
...
gpaste-client add "--separator <string>: add the given separator between each item when merging"

gpaste-client: unrecognized option '--separator <string>: add the given separator between each item when merging'
Usage:
  gpaste-client [history]: print the history with indexes
  gpaste-client history-size: print the size of the history
...
```

**What was expected**
- I expected to see this line of text added to the gpaste gnome shell extension
- when quoting with double-quotes the added string I get back the gpaste-client help https://github.com/Keruspe/GPaste/blob/master/src/client/gpaste-client.c#L147

**What actually happened**
- received a shell error

---

**3) tmux copy buffer**
**How to reproduce**
- copy a string of chars to the tmux copy buffer from the `gpaste-client` help page, namely `--separator <string>: add the given separator between each item when merging`
- try to add it to the clipboard using `gpaste-client` like this
```
echo "$(tmux show-buffer)" | gpaste-client add
```

**What was expected**
- I expected to see this line of text added to the gpaste gnome shell extension

**What actually happened**
- gpaste client treated that piece of text as invalid and showed the gpaste-client help https://github.com/Keruspe/GPaste/blob/master/src/client/gpaste-client.c#L147

---

**Software versions**
```
Desktop: Gnome 3.22.3 Distro: Arch Linux

gnome-shell 3.22.3-1

gpaste 3.22.3-1

gnome-terminal 3.22.1-1

bash 4.4.012-2

zsh 5.3.1-1
```

**Comment by Keruspe** [comment]
Hi,

Fyi, I didn't ignore this bug, I was just busy finishing up 3.24.
This one is next in my TODO once 3.24 is released. Thanks for the detailed description!

**Comment by stefancocora** [comment]
Sounds great ! 👍 
Re detailed description: it is the least I can do since my C skills are not up to the task of attempting a PR :)

**Comment by Keruspe** [comment]
1) Actually, the text is not considered invalid, the cli is just not supposed to work that way.

```
gpaste-client add "foobar" # works
echo "foobar" | gpaste-client # does exactly the same
echo "foobar" | gpaste-client add # not supported
```

I could support that in the next release though, that's not very difficult to do.

**Comment by Keruspe** [comment]
2) When not using quotes, `gpaste-client add <strings> foo` is equivalent in shell language to "cat strings | gaste-client add > foo", it gives the contents of the file named strings to gpaste-client add and then puts the output in a file named foo. The part without quote is thus not a GPaste problem.

When using quotes, it's a trickier problem (thus still not a GPaste problem per se). It's actually a getopt problem. getopt is the standard way of handling command line arguments used by basically everyone (like any system program such as ls, cd and friends use it). When you give it something starting with --, it tries to use that as an argument, which is this case doesnt exist. The tradictional workaround is to tell it explicitely you're done giving aruments, and not to try to use the following stuff as arguments, using `--`

This works: `gpaste-client add -- "--separator <string>: add the given separator between each item when merging"`

**Comment by Keruspe** [comment]
3) This is the same issue as 1) actually.

Btw, `echo "$(tmux show-buffer)"` is equivalent to just `tmux show-buffer` I think.

**Comment by Keruspe** [comment]
For 1) and 3), see #206

**Comment by stefancocora** [comment]
Thanks for the clarification @Keruspe ! 👍 
It wasn't clear for me, from reading the docs, that I could use `gpaste-client` without the `add` command line flag, like in your example `echo "foobar" | gpaste-client # does exactly the same`

Using `gpaste-client` without the `add` command line flag works as expected 👍 

```
tmux show-buffer| gpaste-client
```
Tmux show-buffer feeds into gpaste-client exactly as expected now.

I'll keep an eye on #206 to modify my tmux keyboard shortcut bindings when it gets released. ( which will probably happens soon )

**Comment by stefancocora** [comment]
Thanks to your fix in https://github.com/Keruspe/GPaste/issues/206 the `add` flag for `gpaste-client` works as expected, I've just tested it.

```
tmux show-buffer | gpaste-client add
```

**Comment by MarcoDiFrancesco** [comment]
Fixed disabling `Images support` in settings
