### ISSUE TITLE
Focus search input on key press

### ISSUE THREAD

**Issue by BlackYoup** [Keruspe/GPaste#209]
If you are on the interface looking for something and loose the focus of the search input, you have to click again to gain focus of the input.

I guess hitting any key should focus the input again

**Comment by Keruspe** [comment]
Hmm, it's already the case when the search is empty, so I guess it makes sense to do the same when it's not too

**Comment by BlackYoup** [comment]
Thank you! `cave resolve GPaste -x` is on its way!
