### ISSUE TITLE
kind of infinite loop causing journalctl to be spammed

### ISSUE THREAD

**Issue by BlackYoup** [Keruspe/GPaste#211]
I just encountered a weird bug. I think that at some point, I started multiple gpaste-ui instances (I spammed my shortcut because it didn't showed up quickly enough :P, not sure if that's the real issue here)

Right after, I noticed a huge CPU usage and looked at the processes:
![htop](https://cloud.githubusercontent.com/assets/6098160/26804209/779d1ca4-4a47-11e7-972b-ea02e350842c.png)

I looked at `journalctl` and all I could see was this message spammed *a lot*: `Jun 05 23:25:09 exherswag gpaste-ui[31026]: gtk_widget_get_realized: assertion 'GTK_IS_WIDGET (widget)' failed`

Not sure how to reproduce and this is the first time I'm having this.

I killed the gpaste process and everything got back to normal. I didn't tried to start gpaste during this bug.

I'm using gpaste 3.24.0

**Comment by Keruspe** [comment]
Should be fixed in git
