### ISSUE TITLE
Inconsistent toggle button width in settings UI 

### ISSUE THREAD

**Issue by Vorathe** [Keruspe/GPaste#213]
Steps:
1. Open Gpaste
2. Click Settings button in menu
Result: Toggle controls are not the same width as the toggle control in the top left header
Resolution: Layout could accommodate a larger toggle control

Debian 9, x64, Gpaste from official apt sources
GTK Theme: https://github.com/solus-project/evopop-gtk-theme

![screenshot-gpaste](https://user-images.githubusercontent.com/671509/27662933-9c8a4cfe-5c25-11e7-9ed6-965c563eba37.png)
Compare toggle controls Top Left and in Settings UI.

**Comment by Keruspe** [comment]
Probably a regression from the gtk4 compatibility. Will give it a look, thanks !

**Comment by Keruspe** [comment]
I can't seem to be able to reproduce with latest versions and default theme, can you?

**Comment by goncalossilva** [comment]
I have the same issue on Fedora 34, freshly upgraded. Default theme.

![https://i.imgur.com/ajUCDcP.png](https://i.imgur.com/ajUCDcP.png)

**Comment by Keruspe** [comment]
This interface will switch to libadwaita as soon as it's ready, should fix this and make it look better in a general way.
