### ISSUE TITLE
Adapt to mutter 3.26

### ISSUE THREAD

**Issue by jbicha** [Keruspe/GPaste#219]
mutter 3.25.91 is the current development version of mutter to be released with [GNOME 3.26](https://wiki.gnome.org/ThreePointTwentyfive) later this month. The library name has been bumped.

configure.ac

```
-    PKG_CHECK_MODULES(JS_EXTENSION, [mutter-clutter-0 gjs-1.0 >= gjs_required])
+    PKG_CHECK_MODULES(JS_EXTENSION, [mutter-clutter-1 gjs-1.0 >= gjs_required])
```

Like the last time this happened, I can't see that mutter is actually used in the code so maybe that part of the configure check can be dropped?

**Comment by Keruspe** [comment]
Fixed in master.

It is used in the javascript code from the extension, meaning it's a dependency for the extension, which is why it's checked (but only if the extension is enabled)
