### ISSUE TITLE
Posibility to define height of items in preferences

### ISSUE THREAD

**Issue by mperezfr** [Keruspe/GPaste#221]
In preferences it is possible to define max element size (the width) but it is not possible to define the height of the items. I think it would be very useful if you want to see more items (now I can see 21 and I can't scroll on them, and some times 21 items are not enough).

I'm using gpaste 3.22.0 (on Debian 9), I think this option is not available in latests releases, but I'm not sure.

Thanks in advance. MIGUEL

**Comment by Keruspe** [comment]
Hi,

I'm working on the pagination. Meanwhile, you're probably looking for the "max displayed history size" setting

**Comment by mperezfr** [comment]
Thanks for your quick response. I have put "max displayed history size" to 50, but It only show 21 (because the other do not fit in the screen) and I'm not able to scroll down.

**Comment by Keruspe** [comment]
Oh, right, I see what you mean.

I'm afraid you'll have to wait for the pagination stuff to land then. (Note that it's already there for the gnome-shell extension).

For now, I think the search feature can cover most of the needs (also, the command line doesn't have a limit)

**Comment by mperezfr** [comment]
Thank you very much

**Comment by Keruspe** [comment]
Closing as #169 already covers this issue
