### ISSUE TITLE
GPaste gnome shell extension doesn't show

### ISSUE THREAD

**Issue by goncalossilva** [Keruspe/GPaste#222]
Fedora 26, Gnome 3.24.2.

"Enable the gnome-shell extension" is checked, but there's no icon in the tray. "Display the history" shortcut doesn't work either. 

What I've tried:
* Disabling all other extensions
* Doing a clean install of GPaste (uninstall and removing local directories)
* Toggling a bunch of different options

Is there a log I can check and / or provide to make it easier to spot the problem? `journalctl /usr/bin/gnome-shell -f` doesn't show anything related with GPaste.

Thanks!

**Comment by Keruspe** [comment]
Hi,

In the quick-rundialog (alt-f2), if you run "lg", do you see GPaste in the etensions pane?

**Comment by goncalossilva** [comment]
Hey, thanks for getting back to me so quickly. No, GPaste is not there regardless of whether "Enable the gnome-shell extension" is checked or not.

**Comment by Keruspe** [comment]
Which version of GPaste do you have installed?
Is the extension itself actually installed? (It’s usually a separate
package)

**Comment by goncalossilva** [comment]
Huh. I feel dumb. Reformatted my HD recently and forgot to install `gnome-shell-extension-gpaste`. Somehow assumed toggling the setting would auto-install it for me.

Sorry for wasting your time... :weary: Thanks for the help!

**Comment by iamshubhshrma** [comment]
> Hi,
> 
> In the quick-rundialog (alt-f2), if you run "lg", do you see GPaste in the etensions pane?

can you explain what does it actually do? i wasn't able to exit whatever opened after "lg" and had to restart to system

**Comment by Keruspe** [comment]
It’s a component from gnome-shell and is not actually linked to GPaste.
You can exit it typing Esc.
