### ISSUE TITLE
Gpaste available from locked gnome shell

### ISSUE THREAD

**Issue by gard** [Keruspe/GPaste#226]
When using the gnome-shell-extension for gpaste the whole clipboard is available from a locked gnome session. This I would think is a security problem?

![screenshot from 2018-01-25 14-45-39](https://user-images.githubusercontent.com/37815/35391467-151f0380-01df-11e8-85f7-bb79ed5e1558.png)

**Comment by gard** [comment]
GNOME Shell 3.26.2
GPaste 3.24.2

**Comment by Keruspe** [comment]
I think this is a bug in the ubuntu lock screen? Using standard gnome
components GPaste doesn’t show when session is locked

**Comment by gard** [comment]
Ok! I will create a bug report there instead. Thx for your feedback!
