### ISSUE TITLE
gpaste hangs for some apps

### ISSUE THREAD

**Issue by albfan** [Keruspe/GPaste#228]
I can't detect exactly the problem but copy/paste from gedit to other apps (like terminal) stops to work or happens minutes before executed and copy/paste on chrome does not work

gpaste is the 3.26.1 https://www.archlinux.org/packages/extra/x86_64/gpaste/

Did you notice something similar? Is there any way to provide feedback on what is happening underneath? 

Uninstalling gpaste all copy/paste starts to work again, but I want to help to triage an fix it

**Comment by Keruspe** [comment]
You could try running the daemon with G_MESSAGES_DEBUG=all in your env to see it anything gets printed out

**Comment by albfan** [comment]
Sure. Let me try it and give feedback. I will upload a screencast to show exactly the problem. Hope that helps to give me a hint. I can work on code and try to fix it

**Comment by albfan** [comment]
I kill gaste-daemon

killall gpaste-daemon

and start it with:

G_MESSAGES_DEBUG=all /usr/lib/gpaste/gpaste-daemon

I cannot reproduce the problem but I have that if I see again the problem. By now I will close it
