### ISSUE TITLE
3.26 - copy images -> 17 gb ram used + 25 % cpu

### ISSUE THREAD

**Issue by andreasio** [Keruspe/GPaste#230]
Hi
Working with libreoffice draw, gpaste gets very heavy, very quickly. I'll disable all pictures, but this can hardly be intended?

![screenshot from 2018-02-06 13-17-48](https://user-images.githubusercontent.com/881055/35859410-4036064e-0b40-11e8-8ee9-607468222169.png)

Image support is enabled , but max ram is set to 30 mb.

![screenshot from 2018-02-06 13-20-01](https://user-images.githubusercontent.com/881055/35859479-7fd87840-0b40-11e8-8ee6-26282ddd79df.png)

![screenshot from 2018-02-06 13-20-45](https://user-images.githubusercontent.com/881055/35859499-9299b4d0-0b40-11e8-90e1-e8cc9503b103.png)

Hope this can be of some sort of help

**Comment by blackjackshellac** [comment]
One thing I find interesting about images and gpaste extension vs gpaste-daemon is that if you copy some bitmap data into the clipboard it doesn't show up in the extension if it's above the max history size, but gpaste-daemon still increases in size.  Also, if the bitmap data does fit in memory it shows up in the gpaste extension (size and timestamp) but if you delete it from the extension the memory usage of gpaste-daemon doesn't decrease to reflect deleting the cached clipboard data.

**Comment by Keruspe** [comment]
Heh, yet another images support problem.

I wonder if people with images-support enabled actually use this feature or are just casualties of such bugs. I might disable it by default I guess.

Anyways, thanks for this report, and your last comments will actually be pretty useful I think to finally nail this one down

**Comment by Keruspe** [comment]
The memory increase even with the item not added to the history allowed me to finally catch the main one in commit f64b1c7b68d5d3b28037668fcdb5cc8405a3326f
Also found two other minor ones while at it ! Will backport at least to 3.24
