### ISSUE TITLE
[enhancement] focus search box in extension

### ISSUE THREAD

**Issue by mattia-b89** [Keruspe/GPaste#231]
I think would be a very useful improvement to usability
focus the search box when you open/recall the gpaste gnome extension

**Comment by Keruspe** [comment]
Hmm, it's already the case when you use the keyboard shortcut. Do you mean when you click on the icon then?

**Comment by mattia-b89** [comment]
Yes, I mean when I click on icon
As you said, using CTRL+ALT+H shortcut, it works as it should
