### ISSUE TITLE
Keyboard-focused history selection.

### ISSUE THREAD

**Issue by kevincox** [Keruspe/GPaste#233]
Right now when opening the gnome shell extension dialog it is a little awkward to select previous history entries. Consider the common (for me) use case of selecting the second most recent history item so I can paste it.

First I open the drop-down (`<Ctrl><Alt>H` by default). This selects puts the cursor in the search bar. I now have two options to select the second item:
* Type some characters from the second item. I don't find this convenient because it requires me to remember (or quickly read) the second item, and find a short sequence of characters which don't appear in the first item.
* Type `<Down><Down>Enter` to select the second item. This is better but is quite a few keypresses for a common case. Also if I change my mind half way through I can't start typing to filter.

I am proposing the following change to make this easier.

* When the dropdown is opened the second item is selected by default. This reduces the common case to hitting `<Enter>`.
* Typing filters the results, no matter which item is "selected". So the search box always has keyboard focus.

The one "weird" thing is why select the second item instead of the first. This is maybe a contentious decision (and selecting the first would still be an improvement), however of the two actions that are currently possible (Select and Delete) I suspect that Select is more common. Since selecting the currently selected item doesn't make sense I would optimize for selecting the second. If the user wants to delete the first item they can simple press `<Up><Del>` which is the same number of keypresses as currently required.

I think this improves the user stories.
* Select second most recent item: `<Ctrl><Alt>H <Enter>`
* Select third most recent item: `<Ctrl><Alt>H <Down> <Enter>`
* Search (unchanged):  `<Ctrl><Alt>H {query} (<Down>)* <Enter>`
* Delete first item: `<Ctrl><Alt>H <Up> <Del>`

**Comment by Keruspe** [comment]
Hello,

Thanks for the suggestion!
One trick you may not know though:
<Ctrl><Alt>H <Ctrl>3
This will select the third item (shortcuts available until the 9th)

**Comment by kevincox** [comment]
Thanks, that is an improvement but I think think the proposal is nicer (and doesn't require changing those shortcuts). Feel free to disagree :)

**Comment by kevincox** [comment]
This isn't perfect either because it doesn't close itself afterwords. My original goal was making quick item switching as quick and simple as possible. Feel free to close this issue if you feel that it is fine how it is.

**Comment by Keruspe** [comment]
There is a setting to tell it to close on select

**Comment by rayperea** [comment]
Hi @kevincox 

This may be a little late but what I've done is create a bash script for moving forward and backward through the clipboard history. Then, I used Gnome keyboard shortcuts to assign a keyboard shortcut to the command

Here is a very simple example of the a script you could create:
`gpaste-client select 1` - Selects the previous history entry
`gpaste-client select 2` - Selects the 2nd history entry

History entries are indexed from 0 - where 0 is the current clipboard entry, 1 is the previous, etc...

I actually went a few steps further and created a bash script that shows allows me to quickly move backward and forward through the history all while showing me the contents of each clipboard history entry before I select it.

I've posted the script to github at:
[https://github.com/rayperea/gpaste-history/blob/master/gpasteHistory.sh](https://github.com/rayperea/gpaste-history/blob/master/gpasteHistory.sh)
