### ISSUE TITLE
Notify a libgpaste client when clipboard changes

### ISSUE THREAD

**Issue by DamienCassou** [Keruspe/GPaste#238]
I would like the Emacs-specific clipboard (called the `kill-ring`) to contain everything added to the system clipboard. I have a working prototype that merges the content of gpaste into the `kill-ring` each time Emacs gets the focus.

Instead of merging a bunch of copied texts from gpaste to Emacs from time to time, I would prefer to add each copied text as soon as it is added to gpaste or the system clipboard.

Is libgpaste providing a register/notify mechanism so I can attach some code to the "new copied text available" event? Another solution would be to bypass gpaste and get notifications from X directly. How is gpaste itself notified when the user copies text in the clipboard?

**Comment by DamienCassou** [comment]
Another solution, much simpler for me, would be that gpaste-client gets a `watch` command that prints to stdout each new copied text as soon as the user copies to the clipboard. Emacs already has a way to get notified when a process outputs to stdout/stderr.

If that is a feature, you would like to get, I could have a look at implementing it with some guidance from you.

**Comment by Keruspe** [comment]
Hi,

GPasteClipboard provides an "owner-change" event (which is basically the same as the GtkClipboard one) which is emitted for each X event.

GPasteClient provides an "update" event which is emitted each time the history changes in the daemon

**Comment by DamienCassou** [comment]
Thank you for your answer. I guess you closing the ticket means you don't want any `watch` command on `gpaste-client`.

**Comment by Keruspe** [comment]
Well, gpaste-client is only a usable cli around libgpaste-client which is nothing more than a wrapper around the DBus interface.

There already are some tools existing such as gdbus which allows you to watch dbus signals, so I don't really see the point. You'd better use the dbus interface if you want that kind of thing, it'll be way easier to parse, as you won't have any parsing to do, the data is already structured

**Comment by DamienCassou** [comment]
@Keruspe thank you so much. I've implemented everything I wanted using D-Bus. And it's so much simpler than my previous implementation. Thanks for the D-Bus binding!
