### ISSUE TITLE
Error while installing GPaste

### ISSUE THREAD

**Issue by harshakokel** [Keruspe/GPaste#239]
Hello,

I am trying to install GPaste on Ubuntu 16.04. I am getting following error.

I have already installed libglib2.0-dev. Can someone help me?

$ ./configure --sysconfdir=/etc
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for ar... ar
checking the archiver (ar) interface... ar
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... no
checking for mawk... mawk
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/home/----/Downloads/gpaste-2.9.1/build-aux/missing: Unknown '--is-lightweight' option
Try '/home/---/Downloads/gpaste-2.9.1/build-aux/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking dependency style of gcc... gcc3
checking whether make supports nested variables... (cached) yes
checking for a sed that does not truncate output... (cached) /bin/sed
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking for gcc option to accept ISO C99... none needed
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for gcc way to treat warnings as errors... -Werror
checking if gcc supports __attribute__(( unused ))... yes
checking if gcc supports __attribute__(( visibility("default") ))... yes
checking if gcc supports -pipe flag... yes
checking if gcc supports -pedantic flag... yes
checking if gcc supports -DANOTHER_BRICK_IN_THE flag... yes
checking if gcc supports -Wall flag... yes
checking if gcc supports -W flag... yes
checking if gcc supports -Wextra flag... yes
checking if gcc supports -Wvla flag... yes
checking if gcc supports -Wundef flag... yes
checking if gcc supports -Wformat=2 flag... yes
checking if gcc supports -Wlogical-op flag... yes
checking if gcc supports -Wsign-compare flag... yes
checking if gcc supports -Wformat-security flag... yes
checking if gcc supports -Wmissing-include-dirs flag... yes
checking if gcc supports -Wformat-nonliteral flag... yes
checking if gcc supports -Wold-style-definition flag... yes
checking if gcc supports -Wpointer-arith flag... yes
checking if gcc supports -Winit-self flag... yes
checking if gcc supports -Wfloat-equal flag... yes
checking if gcc supports -Wmissing-prototypes flag... yes
checking if gcc supports -Wstrict-prototypes flag... yes
checking if gcc supports -Wredundant-decls flag... yes
checking if gcc supports -Wmissing-declarations flag... yes
checking if gcc supports -Wmissing-noreturn flag... yes
checking if gcc supports -Wshadow flag... yes
checking if gcc supports -Wendif-labels flag... yes
checking if gcc supports -Wcast-align flag... yes
checking if gcc supports -Wstrict-aliasing=2 flag... yes
checking if gcc supports -Wwrite-strings flag... yes
checking if gcc supports -Werror=overflow flag... yes
checking if gcc supports -Wp,-D_FORTIFY_SOURCE=2 flag... yes
checking if gcc supports -ffast-math flag... yes
checking if gcc supports -fno-common flag... yes
checking if gcc supports -fdiagnostics-show-option flag... yes
checking if gcc supports -fno-strict-aliasing flag... yes
checking if gcc supports -fvisibility=hidden flag... yes
checking if gcc supports -ffunction-sections flag... yes
checking if gcc supports -fdata-sections flag... yes
checking if gcc supports -Wl,--as-needed flag... yes
checking if gcc supports -Wl,--gc-sections flag... yes
checking whether NLS is requested... yes
checking for intltool >= 0.50.0... 0.51.0 found
checking for intltool-update... /usr/bin/intltool-update
checking for intltool-merge... /usr/bin/intltool-merge
checking for intltool-extract... /usr/bin/intltool-extract
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for perl... /usr/bin/perl
checking for perl >= 5.8.1... 5.22.1
checking for XML::Parser... ok
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.22... yes
checking for GLIB... yes
./configure: line 14431: GLIB_GSETTINGS: command not found
./configure: line 14433: syntax error near unexpected token `$GIR_REQUIRED'
./configure: line 14433: `GOBJECT_INTROSPECTION_REQUIRE($GIR_REQUIRED)'

**Comment by Keruspe** [comment]
Try to run autogen.sh again before

**Comment by harshakokel** [comment]
Ran autogen.sh. It resolved the first error GLIB_GSETTING command not found. but still getting $GIR_REQUIRED error. Log below:

$ ./configure --sysconfdir=/etc
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for ar... ar
checking the archiver (ar) interface... ar
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... no
checking for mawk... mawk
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/home/--/Downloads/gpaste-2.9.1/build-aux/missing: Unknown '--is-lightweight' option
Try '/home/--/Downloads/gpaste-2.9.1/build-aux/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking dependency style of gcc... gcc3
checking whether make supports nested variables... (cached) yes
checking for a sed that does not truncate output... (cached) /bin/sed
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking for gcc option to accept ISO C99... none needed
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for gcc way to treat warnings as errors... -Werror
checking if gcc supports __attribute__(( unused ))... yes
checking if gcc supports __attribute__(( visibility("default") ))... yes
checking if gcc supports -pipe flag... yes
checking if gcc supports -pedantic flag... yes
checking if gcc supports -DANOTHER_BRICK_IN_THE flag... yes
checking if gcc supports -Wall flag... yes
checking if gcc supports -W flag... yes
checking if gcc supports -Wextra flag... yes
checking if gcc supports -Wvla flag... yes
checking if gcc supports -Wundef flag... yes
checking if gcc supports -Wformat=2 flag... yes
checking if gcc supports -Wlogical-op flag... yes
checking if gcc supports -Wsign-compare flag... yes
checking if gcc supports -Wformat-security flag... yes
checking if gcc supports -Wmissing-include-dirs flag... yes
checking if gcc supports -Wformat-nonliteral flag... yes
checking if gcc supports -Wold-style-definition flag... yes
checking if gcc supports -Wpointer-arith flag... yes
checking if gcc supports -Winit-self flag... yes
checking if gcc supports -Wfloat-equal flag... yes
checking if gcc supports -Wmissing-prototypes flag... yes
checking if gcc supports -Wstrict-prototypes flag... yes
checking if gcc supports -Wredundant-decls flag... yes
checking if gcc supports -Wmissing-declarations flag... yes
checking if gcc supports -Wmissing-noreturn flag... yes
checking if gcc supports -Wshadow flag... yes
checking if gcc supports -Wendif-labels flag... yes
checking if gcc supports -Wcast-align flag... yes
checking if gcc supports -Wstrict-aliasing=2 flag... yes
checking if gcc supports -Wwrite-strings flag... yes
checking if gcc supports -Werror=overflow flag... yes
checking if gcc supports -Wp,-D_FORTIFY_SOURCE=2 flag... yes
checking if gcc supports -ffast-math flag... yes
checking if gcc supports -fno-common flag... yes
checking if gcc supports -fdiagnostics-show-option flag... yes
checking if gcc supports -fno-strict-aliasing flag... yes
checking if gcc supports -fvisibility=hidden flag... yes
checking if gcc supports -ffunction-sections flag... yes
checking if gcc supports -fdata-sections flag... yes
checking if gcc supports -Wl,--as-needed flag... yes
checking if gcc supports -Wl,--gc-sections flag... yes
checking whether NLS is requested... yes
checking for intltool >= 0.50.0... 0.51.0 found
checking for intltool-update... /usr/bin/intltool-update
checking for intltool-merge... /usr/bin/intltool-merge
checking for intltool-extract... /usr/bin/intltool-extract
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for perl... /usr/bin/perl
checking for perl >= 5.8.1... 5.22.1
checking for XML::Parser... ok
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.22... yes
checking for GLIB... yes
checking for pkg-config... (cached) /usr/bin/pkg-config
checking pkg-config is at least version 0.16... yes
./configure: line 14671: syntax error near unexpected token `$GIR_REQUIRED'
./configure: line 14671: `GOBJECT_INTROSPECTION_REQUIRE($GIR_REQUIRED)'

**Comment by Keruspe** [comment]
First: Why aren't you using a release tarball, or if you do, why are you trying to run autogen.sh by yourself?
Second: Why on earth are you trying to build version 2.9.1?

**Comment by harshakokel** [comment]
Oh, I see now that there is a later version available. I believe I followed the Readme of this github and it links to https://www.imagination-land.org/posts/2012-12-01-gpaste-released.html. N I just downloaded from there.

**Comment by Keruspe** [comment]
Btw, any reason you're not using the ubuntu packages?
Closing as I guess these last answers are sufficient to solve your issue
