### ISSUE TITLE
gpaste daemon crashed with SIGSEGV in g_type_check_instance_is_a()

### ISSUE THREAD

**Issue by nilands55s** [Keruspe/GPaste#243]
Crashed While pasting an image into LibreOffice Version: 4.2.8.2 Build ID: 420m0(Build:2)
Image is now in the Changes list Twice. 
Ubuntu-Gnome 14.04.3 Linux img-4.4.0-124-generic Was just updated and rebooted. 
Gnome Classic desktop (Fallback/Flashback - Metacity). 
Seems the gpaste daemon is still running despite the crash.
 
AMD Phenom 9750 Quad-Core Processor × 4 
GeForce 8500 GT/PCIe/SSE2
8 G-byte RAM
64 bit OS

**Comment by Keruspe** [comment]
Hi,

Which version of GPaste are you running ?
Do you have any relevant logs or stack trace ?
