### ISSUE TITLE
Gpaste search provider freezes entire session.

### ISSUE THREAD

**Issue by ghost** [Keruspe/GPaste#251]
Gnome's search/launcher interface is already laggy as hell due to fundamental design flaws. You can readily observe this nonsense when you start typing and have the results stutter after three letters and then change on you after about 1 second.  Hopefully a bug has been filed with Gnome-desktop for this, cause the fundamental desktop interface is basically broken.

However, GPaste takes Gnome's brittle interface and wrecks it entirely. If you have a moderate amount of data saved in GPaste (think copying a long spreadsheet), the entire session will freeze up for 5-10 seconds when doing a search. You type three letters and then everything freezes.

GPaste search provider should be updated to exclude longish data from the search until a permanent solution is found.

I've disabled the GPaste provider entirely to avoid this bug.

**Comment by developer91234** [comment]
@gmlshadi I've observed the same behavior and you have to disable the search provider, correct.

Gnome is evil. they could have provided a stock clipboard manager like most DE's or accommodated normal clipboard managers that use tray icons. But no, they did neither to make sure you'll never have a clipboard manager sitting in the panel (unless you develop an extension, which will break with the next release of Gnome, like this one did).

**Comment by Keruspe** [comment]
Cannot reproduce anymore with latest versions
