### ISSUE TITLE
Prepare for GNOME Shell 3.30

### ISSUE THREAD

**Issue by jbicha** [Keruspe/GPaste#252]
GNOME Shell and mutter 3.30 were released this week. The mutter soname was bumped to "3".

Please update gpaste to build against the new releases.

Ubuntu 18.10 has a beta version of GNOME Shell 3.30. Other distros will be packaging it very soon.

**Comment by Keruspe** [comment]
Hi,

It's fixed in this branch: https://github.com/Keruspe/GPaste/tree/gpaste-3.30

Note that GPaste 3.28.2 runs just fine with gnome-shell 3.30
