### ISSUE TITLE
GNOME Shell extension needs updating for 3.31

### ISSUE THREAD

**Issue by jbicha** [Keruspe/GPaste#263]
The top bar icon menu doesn't show up when run with gnome-shell 3.31.90 as tested on Ubuntu 19.04 Alpha.

Also, mutter bumped their library version again (from 3 to 4).

**Comment by jrevillard** [comment]
I just tryid to compile the 3.32 branch and it does not work because of the mutter version for me (Gentoo):

```
checking for mutter-clutter-3 gjs-1.0 >= 1.54.0... no
configure: error: Package requirements (mutter-clutter-3 gjs-1.0 >= 1.54.0) were not met:

No package 'mutter-clutter-3' found
```
