### ISSUE TITLE
Gnome Shell 3.31.91: branch 3.32 does not work 

### ISSUE THREAD

**Issue by jrevillard** [Keruspe/GPaste#264]
I get this error message when the extension starts:

```
mars 08 12:07:35 ordiwork gnome-shell[1637]: Extension "GPaste@gnome-shell-extensions.gnome.org" had error: TypeError: this._construct is not a function
```
```
[root:/home/jerome] 130 # gnome-shell --version
GNOME Shell 3.31.91
```

Best,
Jerome

**Comment by Keruspe** [comment]
It’s not tested yet as I do not have access to a gnome 3.32 box yet

**Comment by Keruspe** [comment]
I'll try to get my hands on some gnome 3.32 before the release, but hopefully e9473969abf6ae457c79cd14233c71d61a3f16f6 will fix this

**Comment by jrevillard** [comment]
Not yet ... ;-)

```
mars 08 17:11:29 ordiwork gnome-shell[624]: Extension "GPaste@gnome-shell-extensions.gnome.org" had error: SyntaxError: bad method definition
```

But I cannot say where .... I have not stack...

Best,
Jerome

**Comment by Keruspe** [comment]
Heh indeed I missed this syntax change, will fix later tonight

**Comment by Keruspe** [comment]
I should get gnome 3.32 by next week.

In the mean time, this last error should now be fixed.

**Comment by Keruspe** [comment]
Last one was a PITA to debug, but works fine now.
