### ISSUE TITLE
Several warnings on journal log due to extension

### ISSUE THREAD

**Issue by simonbcn** [Keruspe/GPaste#268]
```
Arch Linux
GNOME Shell 3.32.0
gpaste 3.32.0
```

```
mar 17 10:05:58 arch-juan gnome-shell[836]: Some code accessed the property 'GPasteStatusIcon' on the module 'statusIcon'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
mar 17 10:05:58 arch-juan gnome-shell[836]: Some code accessed the property 'GPasteDummyHistoryItem' on the module 'dummyHistoryItem'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
mar 17 10:05:58 arch-juan gnome-shell[836]: Some code accessed the property 'GPasteSearchItem' on the module 'searchItem'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
mar 17 10:05:58 arch-juan gnome-shell[836]: Some code accessed the property 'GPastePageSwitcher' on the module 'pageSwitcher'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
....
mar 17 10:05:59 arch-juan gnome-shell[836]: Some code accessed the property 'GPasteUiItem' on the module 'uiItem'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
mar 17 10:05:59 arch-juan gnome-shell[836]: Some code accessed the property 'GPasteEmptyHistoryItem' on the module 'emptyHistoryItem'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
mar 17 10:05:59 arch-juan gnome-shell[836]: Some code accessed the property 'GPasteAboutItem' on the module 'aboutItem'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
mar 17 10:05:59 arch-juan gnome-shell[836]: Some code accessed the property 'GPasteStateSwitch' on the module 'stateSwitch'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
mar 17 10:05:59 arch-juan gnome-shell[836]: Some code accessed the property 'GPasteItem' on the module 'item'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
mar 17 10:05:59 arch-juan gnome-shell[836]: Some code accessed the property 'GPasteDeleteItemPart' on the module 'deleteItemPart'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
mar 17 10:05:59 arch-juan gnome-shell[836]: Some code accessed the property 'GPasteDeleteButton' on the module 'deleteButton'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
mar 17 10:05:59 arch-juan gnome-shell[836]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received
                                            setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:70:30
mar 17 10:05:59 arch-juan gnome-shell[836]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received
                                            setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:70:30
mar 17 10:05:59 arch-juan gnome-shell[836]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received
                                            setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:70:30
mar 17 10:05:59 arch-juan gnome-shell[836]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received
                                            setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:70:30
mar 17 10:05:59 arch-juan gnome-shell[836]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received
                                            setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:70:30
mar 17 10:05:59 arch-juan gnome-shell[836]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received
                                            setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:70:30
mar 17 10:05:59 arch-juan gnome-shell[836]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received
                                            setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:70:30
mar 17 10:05:59 arch-juan gnome-shell[836]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received
                                            setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:70:30
mar 17 10:05:59 arch-juan gnome-shell[836]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received
                                            setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:70:30
mar 17 10:05:59 arch-juan gnome-shell[836]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received
                                            setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:70:30
mar 17 10:05:59 arch-juan gnome-shell[836]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received
                                            setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:70:30
mar 17 10:05:59 arch-juan gnome-shell[836]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received
                                            setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:70:30
mar 17 10:05:59 arch-juan gnome-shell[836]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received
                                            setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:70:30
mar 17 10:05:59 arch-juan gnome-shell[836]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received
                                            setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:70:30
mar 17 10:05:59 arch-juan gnome-shell[836]: Some code accessed the property 'GPastePageItem' on the module 'pageItem'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
```

**Comment by Keruspe** [comment]
Looking into the setIndex one, fixed the others

**Comment by Keruspe** [comment]
Hmm, what is your max history size, your max displayed history size, and how much items are there in your history, when the setIndex warnings appear?

**Comment by simonbcn** [comment]
![captura_20190317_155733](https://user-images.githubusercontent.com/428231/54493204-687c8f80-48cd-11e9-8f11-b60779fa3d76.png)

**Comment by Keruspe** [comment]
Thanks, and how many items do you have in your history?

**Comment by simonbcn** [comment]
72

**Comment by dagufri** [comment]
I'm also getting this error in /var/log/syslog. The screen went black for a while. I had 3 items in history.

Jul 13 10:13:06 kled NetworkManager[657]: <info>  [1594627986.5855] agent-manager: req[0x556932934ed0, :1.228/org.gnome.Shell.NetworkAgent/1000]: agent registered
Jul 13 10:13:06 kled gnome-shell[1382]: JS ERROR: TypeError: iconsContainer.add_actor is not a function#012createIconsContainer@/home/daniel/.local/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js:181:5#012createTray@/home/daniel/.local/share/gnome-shell/
extensions/TopIcons@phocean.net/extension.js:185:5                                                                                                                                                                                                                          
Jul 13 10:13:06 kled gnome-shell[1382]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received#012setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:80:30
Jul 13 10:13:06 kled gnome-shell[1382]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received#012setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:80:30
Jul 13 10:13:06 kled gnome-shell[1382]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received#012setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:80:30
Jul 13 10:13:06 kled gnome-shell[1382]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received#012setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:80:30
Jul 13 10:13:06 kled gnome-shell[1382]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received#012setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:80:30
Jul 13 10:13:06 kled gnome-shell[1382]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received#012setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:80:30
Jul 13 10:13:06 kled gnome-shell[1382]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received#012setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:80:30
Jul 13 10:13:06 kled gnome-shell[1382]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received#012setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:80:30
Jul 13 10:13:06 kled gnome-shell[1382]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received#012setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:80:30
Jul 13 10:13:06 kled gnome-shell[1382]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received#012setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:80:30
Jul 13 10:13:06 kled gnome-shell[1382]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received#012setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:80:30
Jul 13 10:13:06 kled gnome-shell[1382]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received#012setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:80:30
Jul 13 10:13:06 kled gnome-shell[1382]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received#012setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:80:30
Jul 13 10:13:06 kled gnome-shell[1382]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received#012setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:80:30
Jul 13 10:13:06 kled gnome-shell[1382]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received#012setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:80:30
Jul 13 10:13:06 kled gnome-shell[1382]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received#012setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:80:30
Jul 13 10:13:06 kled gnome-shell[1382]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.GPaste.Error: invalid index received#012setIndex/<@/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/item.js:80:30

$ dconf dump /org/gnome/GPaste/
[/]
close-on-select=false
max-memory-usage=uint64 100
history-name='history'
synchronize-clipboards=true
track-changes=true
trim-items=false
track-extension-state=true
upload='<Ctrl><Alt>U'
max-history-size=uint64 500
max-displayed-history-size=uint64 20
launch-ui='<Ctrl><Alt>G'
images-support=true
primary-to-history=true
growing-lines=true
sync-clipboard-to-primary='<Ctrl><Alt>O'
show-history='<Alt>p'
save-history=false
sync-primary-to-clipboard='<Ctrl><Alt>P'

$ apt-cache policy gpaste
gpaste:
  Installed: 3.30.2-1
  Candidate: 3.30.2-1
  Version table:
 *** 3.30.2-1 500
        500 http://debian.snt.utwente.nl/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status

$ cat /etc/debian_version 
10.4
