### ISSUE TITLE
How to start gpaste-daemon at boot ?

### ISSUE THREAD

**Issue by Paviluf** [Keruspe/GPaste#269]
I use Fedora 29 and I installed gpaste and gpaste-ui from the repo but the gpaste-daemon doesn't seem to launch at boot. Note that I don't want to use the Gnome shell extension. How can I make the daemon launch at boot ? Thank you.

**Comment by Keruspe** [comment]
Hi,

You can run `gpaste-client start` at your session startup, this will activate the daemon

**Comment by Paviluf** [comment]
Ok, thank you !
