### ISSUE TITLE
gnome 3.34 mutter new clipboard implementation

### ISSUE THREAD

**Issue by kapouer** [Keruspe/GPaste#273]
Hi,
are you aware of this ?
https://gitlab.gnome.org/GNOME/mutter/merge_requests/320

i figured you might be concerned ;)

**Comment by Keruspe** [comment]
Yes saw that, didn’t check how we could use it yet though. I have a couple
of other things to finish first

**Comment by Keruspe** [comment]
Don't think it can be used in GPaste
