### ISSUE TITLE
Keyboard shortcuts in Cinnamon

### ISSUE THREAD

**Issue by tacticz** [Keruspe/GPaste#274]
Hello,
I've successfully installed GPaste on a Debian Buster RC1 release running Cinnamon as DE.
It was possible to install straight from the Debian repos using:
`$ sudo apt install gpaste gnome-shell-extensions-gpaste`

Then, downloading and activating the "GPaste Reloaded" applet made a GPaste icon available in the panel. It is possible to access the GPaste history, as well as other GPaste functionalities, by clicking and right clicking on this icon... So far so good.

Unfortunately I was NOT able to find a way to get GPaste's keyboard shortcuts to work :-(
Which of course is a major drawback on GPaste functionality since 98% of GPaste usage would be executed through keyboard commands. I mean, having to use the mouse to click on the icon and scroll the history to paste an item from it makes things much less usable than having a keystroke popping the history, using the arrow keys to select the needed item and typing "return" to select it for example, is the way one would expect to use a tool like GPaste.

I've reviewed a few other issues reported here, but since Cinnamon has separated from GNOME, I was wondering if there is any possibility to assign keyboard shortcuts to GPaste in the environment I'm working with?

I'd appreciate any hint on how to achieve this since I'm really eager to benefit from GPaste capabilities instead of the limited ones offered by Parcelite which I was using until now and I also would like to avoid going to CopyQ which seems much more heavy.

Thank you very much.

**Comment by LinuxOnTheDesktop** [comment]
I have the same problem, also on Cinnamon.

**Comment by simonwiles** [comment]
I just bound `Ctrl + Ins` to `gpaste-client ui` using Cinnamon's keyboard settings, and it works well enough for me. "GPaste Reloaded" has options too -- perhaps they're new since this issue was opened?

**Comment by Keruspe** [comment]
I'm not really familiar with cinnamon, but if they follow the dbus interface from gnome-shell, it should work, using X or wayland.
If they don't provide the interface anymore and you're running X, it should work too.
If they still provide it but they didn't follow the API changes from gnome-shell, or if you're running wayland, then it won't work. They really shouldn't do that

Most shortcuts should be available through commands as suggested though
