### ISSUE TITLE
Keyboard shortcuts not working in Ubuntu 19.04

### ISSUE THREAD

**Issue by memeplex** [Keruspe/GPaste#275]
I know the current version in Ubuntu/Debian is outdated so the gnome shell extension is broken.

But I'm also unable to make the shortcuts work, they appear under Settings/Keyboard but do nothing at all.

Are both problems related? Is it necessary to enable the extension to get the shortcuts working?

**Comment by gnuget** [comment]
I compiled the latest version (3.32.0) and I have the same error, so it is not related.

**Comment by gnuget** [comment]
I temporal workaround is add a new shortcut (you need to go to `settings` -> `keyboard` and there Add a new shortcut with the following command:

```
gpaste-client show-history
```
That command will display the gnome-shell  dialog.

Hope it helps. 

David.

**Comment by vimalaguti** [comment]
> I temporal workaround is add a new shortcut (you need to go to `settings` -> `keyboard` and there Add a new shortcut with the following command:
> 
> ```
> gpaste-client show-history
> ```
> 
> That command will display the gnome-shell dialog.
> 
> Hope it helps.
> 
> David.

nope, on ubuntu 18.04 I have to use gpaste-client ui
The show-history command doesn't work

**Comment by cmoetzing** [comment]
Same here. Ubuntu 18.04 and neither does the shortcut work not does something happen when I issue the command `gpaste-client show-history`. The command simply returns with not error and return code 0 but no UI appears. Anything we provide as error analysis?

**Comment by suside** [comment]
Confirmed on Ubuntu 19.10 + Wayland
It seems the shortcut itself works, but I had to install `sudo apt install gnome-shell-extensions-gpaste` and reload gnome shell. From now on `gpaste-client show-history` works as expected.

**Comment by cmoetzing** [comment]
Installing the extension did the trick. After installing the "Show gnome shell extension" option was set to off again. After enabling it it worked. I had searched the extension in "Ubuntu Software" but it didn't show. Is it possible to display a warning when switching "Show gnome shell extension" to "On" and the extension isn't installed? It is very misleading if you can turn it on without any effect.

**Comment by Zwyx** [comment]
Hi all, I wanted to share my experience here as I believe it could help future users.

I'm on Ubuntu 22.04 and I installed GPaste by simply installing `gnome-shell-extension-gpaste` with its dependencies.

The shortcut to display the clipboard history wasn't working all the time, depending on which window had the focus: it was working when Chrome had the focus, but not when the desktop, Nautilus, or the terminal had it. (It might be related to https://github.com/Keruspe/GPaste/issues/387, but I don't have any error message when I start `gpaste-deamon`.)

gnuget's workaround did the trick for me, now the history shows up all the time :slightly_smiling_face: 

Thanks for making GPaste, Keruspe, let me know if you'd like me to create an Issue for this (I definitely don't need it, the workaround is all I need).
