### ISSUE TITLE
gpaste ui won't launch on RHEL v8

### ISSUE THREAD

**Issue by GrayCatCode** [Keruspe/GPaste#277]
I just installed GPaste v3.22.6 on RHEL v8 and get the following error when executing the `gpaste-client ui` command:

BASh v4.4.19 in ~ (8) >> gpaste-client ui

** (gpaste-client:7345): CRITICAL **: 13:15:57.381: Couldn't spawn Ui: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.GPaste.Ui was not provided by any .service files

To be fair, I'm getting the same error on CentOS v7.

**Comment by Keruspe** [comment]
I guess gpaste-ui is provided by another packager on RHEL and that package isn't installed?
