### ISSUE TITLE
No gpaste after install

### ISSUE THREAD

**Issue by tuxedotje** [Keruspe/GPaste#287]
did sudo dnf install gpaste (on Fedora 31 beta)
does install something:
Installed:
  gpaste-3.34.1-1.fc31.x86_64                                   gpaste-libs-3.34.1-1.fc31.x86_64                                  
Do not see any icon, typing gpaste in terminal does not work to start gpaste,
which gpaste  gives:
/usr/bin/which: no gpaste in (/home/jaap/.local/bin:/home/jaap/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin)

Does gpaste work on fedora 31?

**Comment by MintYale** [comment]
try these:
```
sudo dnf install gpaste*

sudo dnf install gnome-shell-extension*

reboot
```

**Comment by Keruspe** [comment]
The cli client is called `gpaste-client`, not `gpaste` as the latter conflicted with coreutils on some distros
