### ISSUE TITLE
Cinnamon freezes when copying with long history

### ISSUE THREAD

**Issue by Fabian42** [Keruspe/GPaste#293]
I had about 7000 entries in the GPaste history. Whenever I copied something, the entire desktop environment (Cinnamon 3.2.7 on Debian 9.11) froze for about 5 seconds.

Reducing the maximum history length to 100 works around this, but that's not a nice solution, since I do want a long history. And if this problem scales linearly, that still means a freeze of 5 frames. A full 65536 entry list would probably freeze the DE for almost a minute.

I don't even know why it lags at all, since "detect growing lines" is off and nothing else should do anything with the full history, except searching. And especially it should run in a separate thread from Cinnamon.

GPaste version 3.22.0
I'm using the applet "GPaste reloaded", version 2.6.

**Comment by Keruspe** [comment]
I suppose "GPaste reloaded" uses the "sync" variant of the GPaste interface. It's not at al affiliated to this repository
