### ISSUE TITLE
GPaste interfers with selection in LyX

### ISSUE THREAD

**Issue by lemmy** [Keruspe/GPaste#294]
![LyxAndGPaste](https://user-images.githubusercontent.com/88777/72272420-70848900-35dd-11ea-90d0-917ccc0c8f93.gif)

```bash
markus    2582  0.0  0.0 636692 20700 ?        Ssl  08:54   0:00 /usr/lib/x86_64-linux-gnu/gpaste/gpaste-daemon
markus    5554  0.0  0.0  14760  1108 pts/0    S+   09:59   0:00 grep --color=auto gpaste-daemon
markus@avocado:~$ dpkg -l |grep gpaste
ii  gir1.2-gpaste-1.0                          3.28.0-2                                            amd64        GObject introspection data for the libgpaste6 library
ii  gnome-shell-extensions-gpaste              3.28.0-2                                            all          GPaste extension for GNOME Shell
ii  gpaste                                     3.28.0-2                                            amd64        Clipboard management system for GNOME
ii  libgpaste9                                 3.28.0-2                                            amd64        Clipboard management system for GNOME - library
markus@avocado:~$ dpkg -l |grep lyx
ii  fonts-lyx                                  2.3.3-1~bionic~ppa1                                 all          TrueType versions of some TeX fonts used by LyX
ii  lyx                                        2.3.3-1~bionic~ppa1                                 amd64        Document Processor
ii  lyx-common                                 2.3.3-1~bionic~ppa1                                 all          Architecture-independent files for LyX
```

Filed for LyX at https://www.lyx.org/trac/ticket/11715

**Comment by xero-lib** [comment]
I am having the same issue, but everything I select is immediately copied to the clipboard.

**Comment by xero-lib** [comment]
@lemmy do you have primary selection affects clipboard disabled?

**Comment by scottkosty** [comment]
@xero-lib Have you by chance tried the freshly released LyX 2.3.5? I made a commit [here](https://git.lyx.org/?p=lyx.git;a=commit;h=7a158055fe6c05763f88ddb61a9c02b42614091d), which is part of 2.3.5, that I think has a chance to help with the problem.

**Comment by xero-lib** [comment]
@scottkosty I solved that one myself by editing the conf file. It had a malformed 'growing lines' script. The issue now is that I cant get image persistence in the clipboard. But that's a subject for a different thread.

**Comment by scottkosty** [comment]
@xero-lib Good to know. What did you edit in the conf file? This might be helpful to others.
