### ISSUE TITLE
GPaste does not copy correctly on GNOME 3.34 Wayland

### ISSUE THREAD

**Issue by heftig** [Keruspe/GPaste#295]
1. Open a Wayland application (e.g. GEdit)
2. Copy some text from this application (so it owns the clipboard)
3. Verify you can paste the text
4. Use the GPaste shell extension to select another text
5. **The clipboard is now empty**
6. Switch window focus to another application and back
7. You can now paste the text copied by GPaste

Although I think there's something screwy with the shell's focus and clipboard handling here, it normally doesn't matter as you always have to switch focus to copy between two applications. The GPaste extension triggering the gpaste daemon (an X11 application?) to copy something is a special case which has no focus transfer.

gpaste 3.34.1
mutter 3.34.3-30-g4959ae8bc
gnome-shell 3.34.3
gtk 3.24.13

**Comment by garnacho** [comment]
Clipboard management seems indeed left out to the GPaste daemon in the extension, and the daemon indeed seems to use the x11 GDK backend.

I expect mutter to notice the x11 clipboard selection owner change:
https://gitlab.gnome.org/GNOME/mutter/blob/master/src/x11/meta-x11-selection.c#L343
And to set it as the current owner:
https://gitlab.gnome.org/GNOME/mutter/blob/master/src/x11/meta-x11-selection.c#L299

This owner change notification to a X11 source does nothing within mutter face to X11, as X11 clients are expected to talk directly with the current X11 clipboard owner (GPaste daemon in this case):
https://gitlab.gnome.org/GNOME/mutter/blob/master/src/x11/meta-x11-selection.c#L377

But the ownership change would be handled on the wayland side, and any currently focused wayland client would receive a new wl_data_offer for the current clipboard data:
https://gitlab.gnome.org/GNOME/mutter/blob/master/src/wayland/meta-wayland-data-device.c#L1925

Without knowing much about GPaste internals and ignoring other possible players here, it seems to me that mutter code should handle the situation correctly.

**Comment by RussianNeuroMancer** [comment]
Issue is still reproducible with gpaste 3.36.3 and mutter 3.36.1.

**Comment by heftig** [comment]
Fixed by https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1204

**Comment by Keruspe** [comment]
Wow, that’s nice!
I was convinced this was a mutter problem but couldn’t prove it
