### ISSUE TITLE
Cannot start org.gnome.GPaste service on Arch under Sway

### ISSUE THREAD

**Issue by gergelypolonkai** [Keruspe/GPaste#296]
According to the logs:

```
$ systemctl --user status org.gnome.GPaste.service
● org.gnome.GPaste.service - GPaste daemon
     Loaded: loaded (/usr/lib/systemd/user/org.gnome.GPaste.service; static; vendor preset: enabled)
    Drop-In: /home/polesz/.config/systemd/user/org.gnome.GPaste.service.d
             └─override.conf
     Active: failed (Result: exit-code) since Fri 2020-02-21 09:11:51 CET; 5s ago
    Process: 296226 ExecStart=/usr/lib/gpaste/gpaste-daemon (code=exited, status=1/FAILURE)
   Main PID: 296226 (code=exited, status=1/FAILURE)

feb 21 09:11:51 machina systemd[604]: Starting GPaste daemon...
feb 21 09:11:51 machina gpaste-daemon[296226]: cannot open display: 
feb 21 09:11:51 machina systemd[604]: org.gnome.GPaste.service: Main process exited, code=exited, status=1/FAILURE
feb 21 09:11:51 machina systemd[604]: org.gnome.GPaste.service: Failed with result 'exit-code'.
feb 21 09:11:51 machina systemd[604]: Failed to start GPaste daemon.
```

Starting the daemon (`/usr/lib/gpaste/gpaste-daemon`) from a terminal works fine and if i do, `gpaste-client` can happily connect to the service.

Also, creating an override configuration in `~/.config/systemd/user/org.gnome.GPaste.service.d/override.conf` with this content helps:

```
[Service]
Environment=XAUTHORITY=/home/polesz/.Xauthority
Environment=DISPLAY=:0
```

(Although i’m not sure if `XAUTHORITY` really needs to be set.)

**Comment by helge000** [comment]
I can run the daemon from a shell:

```shell
$ /usr/libexec/gpaste/gpaste-daemon --gapplication-service
```

This way you can get `gpaste-client ui` to work. However, it does not do anything - I guess it needs a gnome-shell to work after all:

```
/usr/libexec/gpaste/gpaste-daemon --gapplication-service

(gpaste-daemon:357056): GPaste-WARNING **: 14:59:48.898: Couldn't grab keybindings with gnome-shell: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
```

**Comment by Keruspe** [comment]
Wrt the first issue: this means that your dbus environment is up to date, but not your systemd environment. This is why autospawning it via dbus works, but starting the systemd service doesn't.

The warning for keybindings just tell you that it wouldn't use gnome-shell to grab the keybinding, but if configured properly when compiling it, it has another builtin x11 keybinder.

**Comment by Keruspe** [comment]
But yeah, on wayland, as far as I can there's no way of creating a clipboard manager so for now GPaste forces X11, and (ab)uses mutter's ability to sync the Xwayland and the wayland clipboards

**Comment by helge000** [comment]
@Keruspe - thanks for clearing this up:
>and (ab)uses mutter's ability to sync the Xwayland and the wayland clipboards 

I read from this gpaste requires a gnome-shell?

@gergelypolonkai - Maybe a workaround for you:
Since I desperately needed a clipboard manager for sway, I went the [wl-clipboard](https://github.com/bugaevc/wl-clipboard) / [Clipman](https://github.com/yory8/clipman.git) route - this works very well for me:

```
exec wl-paste -t text --watch clipman store 
bindsym $mod+c exec clipman pick -t wofi
```

**Comment by Keruspe** [comment]
For wayland, GPaste basically requires gnome-shell yes. Unless you know of a way to watch for global clipboards events on wayland

**Comment by gergelypolonkai** [comment]
No, but maybe it would be a great addition to wlroots / sway…

**Comment by gergelypolonkai** [comment]
@helge000 wl-clipboard+Clipman is a nice alternative indeed. I’ll keep GPaste for my GNOME notebook only, then.
