### ISSUE TITLE
Question - paste into focused control 

### ISSUE THREAD

**Issue by yuriw** [Keruspe/GPaste#304]
I am not sure if this option exist as so far could not find it.

Use case:
User select say for example URL filed in a browser
Clicks in Gpaste icon 
Selects a desired item 
The desired item automatically pasted into  URL filed in a browser

Is this possible?

PS:  Thx for a great extension !

**Comment by yuriw** [comment]
@afn  and @Keruspe

**Comment by Keruspe** [comment]
Hello,

See e.g. https://github.com/Keruspe/GPaste/issues/119 for an explanation of why we won't support such a thing.
There is no way to reliably implement this

**Comment by yuriw** [comment]
@Keruspe thx for the answer.

Maybe it will be possible in the future as it's very helpful
Wonder how Diodon implemented this functionality ?

**Comment by Keruspe** [comment]
Same feature was present in GPaste several years ago. Diodon implemented it the same way. There were too many reports of it being unreliable so I decided to drop it until there’s a proper alternative
