### ISSUE TITLE
./configure not in tarball

### ISSUE THREAD

**Issue by Rmano** [Keruspe/GPaste#305]
Good afternoon, and thanks for the application!

I have problems with the version that Ubuntu 18.04 ships (3.28.0 --- Gnome shell is 3.28.4 here), which seems to go into an infinite loop when copying images; I checked the logs and it seems that the version 3.28.3 should fix the problem. So I downloaded it, but I can't compile.

The instructions say that if are building from a tarball, you should skip the `./autogen.sh` part (which fails on me on Ubuntu 18.04); but then the `./configure` script is not there...:

```bash
[romano:~/software … ils/GPaste-3.28.3] % ls
AUTHORS     ChangeLog     COPYING  m4           man   po         src    THANKS  tools
autogen.sh  configure.ac  data     Makefile.am  NEWS  README.md  tests  TODO
```

Trying with GPaste-3.28.3.tar.gz and GPaste-3.36.3.tar.gz (BTW, can I just use the last version or should I use the one that matches my gnome-shell?)

**Comment by Keruspe** [comment]
How did you download the tarball?

**Comment by Rmano** [comment]
From https://github.com/Keruspe/GPaste/archive/v3.28.3.tar.gz , following the release tab in GitHub... wrong place?

**Comment by Keruspe** [comment]
Github only makes a tarball from the git repository which doesn’t contain
generated files.

**Comment by Rmano** [comment]
Ok. Seen it; I had to use the tarballs from https://www.imagination-land.org/tags/GPaste.html 

Thank you, sorry for the hassle. Will close. If you have a bit of time: can I compile the last one or should I take the version matching my gnome-shell?

**Comment by Keruspe** [comment]
You should take GPaste 3.X for gnome-shell 3.X (the third number doesn’t
matter, you can take the last one, but the first two should be the same)

**Comment by Rmano** [comment]
Thanks!

**Comment by Rmano** [comment]
...sorry to plaster again. Is there a list of dependency one have to compile? I am stuck on gnome-keybinder (after solving a couple of them...)

**Comment by Keruspe** [comment]
I think there’s a way to tell your package manager to install the
dependencies required to build a package, as they already maintain that
list to build the official packages.
The list of packages depends on the distribution...
Wrt gnome-keybinder all I can tell you is that it’s part of
gnome-control-center

**Comment by Rmano** [comment]
Hi --- I found a way to show the list; I'll put it here --- anyway, I think it would be nice to have a dependency list to ease the life if you are compiling for a distro that does not support it natively... 

```bash
θ67° [romano:~/software … s/gpaste-3.28.3] % apt-rdepends --build-depends --follow=DEPENDS gpaste gnome-shell-extensions-gpaste 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gpaste
  Build-Depends: appstream-util (>= 0.7.4)
  Build-Depends: debhelper (>= 10)
  Build-Depends: gnome-control-center-dev
  Build-Depends: gobject-introspection (>= 1.48.0~)
  Build-Depends: intltool
  Build-Depends: libappstream-glib-dev
  Build-Depends: libclutter-1.0-dev
  Build-Depends: libdbus-1-dev
  Build-Depends: libgirepository1.0-dev (>= 1.48.0~)
  Build-Depends: libgjs-dev (>= 1.48.0)
  Build-Depends: libglib2.0-dev (>= 2.56.0~)
  Build-Depends: libgtk-3-dev (>= 3.20)
  Build-Depends: libmutter-2-dev
  Build-Depends: libxcb-keysyms1-dev
  Build-Depends: libxcb-xtest0-dev
  Build-Depends: libxml2-dev
  Build-Depends: libxtst-dev
  Build-Depends: pkg-config (>= 0.29~)
  Build-Depends: valac (>= 0.32)
gnome-shell-extensions-gpaste
  Build-Depends: appstream-util (>= 0.7.4)
  Build-Depends: debhelper (>= 10)
  Build-Depends: gnome-control-center-dev
  Build-Depends: gobject-introspection (>= 1.48.0~)
  Build-Depends: intltool
  Build-Depends: libappstream-glib-dev
  Build-Depends: libclutter-1.0-dev
  Build-Depends: libdbus-1-dev
  Build-Depends: libgirepository1.0-dev (>= 1.48.0~)
  Build-Depends: libgjs-dev (>= 1.48.0)
  Build-Depends: libglib2.0-dev (>= 2.56.0~)
  Build-Depends: libgtk-3-dev (>= 3.20)
  Build-Depends: libmutter-2-dev
  Build-Depends: libxcb-keysyms1-dev
  Build-Depends: libxcb-xtest0-dev
  Build-Depends: libxml2-dev
  Build-Depends: libxtst-dev
  Build-Depends: pkg-config (>= 0.29~)
  Build-Depends: valac (>= 0.32)
```
