### ISSUE TITLE
how to put it in the system tray

### ISSUE THREAD

**Issue by ORESoftware** [Keruspe/GPaste#309]
I want gpaste to appear here:

![Screenshot from 2020-05-06 08-47-02](https://user-images.githubusercontent.com/11139560/81198305-2c473b00-8f76-11ea-8d0e-fa2aee0c6da5.png)

otherwise it's too hard to quickly pull the application up?

**Comment by Keruspe** [comment]
Did you try https://github.com/Keruspe/gpaste-applet ?

**Comment by ORESoftware** [comment]
the ctrl-alt-g thing works well to open the app, so the tray icon is unnecessary for me I think, although I think a tray icon should be an option in the main UI, if that's possible! that would be nice to toggle tray icon on/off.

**Comment by ORESoftware** [comment]
It would be nice if <kbd>ctrl</kbd>-<kbd>alt</kbd>-<kbd>g</kbd> would minimizing the app also if it's open / in front.
