### ISSUE TITLE
Ubuntu 19 - program closes/crashes when I click any item in the list

### ISSUE THREAD

**Issue by ORESoftware** [Keruspe/GPaste#310]
When I click any item in the main list, the program closes (I assume it's crashing). Is it logging anything to syslog? I can share the logs if that helps.  I just want to copy an item from the clipboard.
Perhaps this is intended behavior, however. If so, how can I keep the program open?

![Screenshot from 2020-05-06 09-08-32](https://user-images.githubusercontent.com/11139560/81200800-51897880-8f79-11ea-826c-4e1df586f72d.png)

**Comment by Keruspe** [comment]
It’s not a crash, it’s a feature. The selected item is now in your
clipboard and you can paste it

**Comment by ORESoftware** [comment]
Yeah thanks I see the settings option "Close UI on Select", I turned it off, thanks

**Comment by ORESoftware** [comment]
BTW, please put on option to "view app logs" in the UI, then users can debug things
