### ISSUE TITLE
Feature request: Support for marking favorite items

### ISSUE THREAD

**Issue by sbuvaneshkumar** [Keruspe/GPaste#311]
There are times where we have to copy paste the same item time to time.
It would be nice if we can mark the item as favorite in GPaste, so it can stay forever in clipboard history.

**Comment by pinnerup** [comment]
I came here to suggest the exact same feature :)

**Comment by jacostag** [comment]
I also want that :P but there is already a request for this, this one should be marked as dup
https://github.com/Keruspe/GPaste/issues/217
