### ISSUE TITLE
./autogen.sh: line 6: autoreconf: command not found

### ISSUE THREAD

**Issue by fiko** [Keruspe/GPaste#313]
Once I run `./autogen.sh`, it says this error :
![image](https://user-images.githubusercontent.com/32075735/82107467-20b3fb00-9752-11ea-8b8d-5aeb25141594.png)

I'm using Ubuntu 20.04, any solution?

**Comment by Keruspe** [comment]
If you're running ubuntu, you should use the ubuntu package nless you have a good reason to build it from sources
