### ISSUE TITLE
Crtl-Alt-U does not work 

### ISSUE THREAD

**Issue by yuriw** [Keruspe/GPaste#315]
Did anybody see it's working ?

Would it show URL for a resulting paste?

As a possible feature request - it'd very useful to ingrate gpaste functionality into right mouse desktop click options

**Comment by Keruspe** [comment]
Do you have wgetpaste installed?

**Comment by yuriw** [comment]
@Keruspe no and don't see it for ubuntu

**Comment by Keruspe** [comment]
You either need to install it or to configure a different command to upload to a paste service

**Comment by yuriw** [comment]
is there a way to install it on ubutnu ?

**Comment by Keruspe** [comment]
I don’t use Ubuntu so I don’t know
