### ISSUE TITLE
gpaste tracks everything that is selected character by character

### ISSUE THREAD

**Issue by rayzorben** [Keruspe/GPaste#322]
Maybe it is a combination of settings I have wrong, When I select something, every character gets its own entry when I select it.

Yes, I want 'copy on select", but it should only do it on mouseup.

Do I have it configured incorrectly? This image shows my options and some of the behavior I am seeing

![image](https://user-images.githubusercontent.com/7737834/92839896-529e3c80-f395-11ea-98a0-ef2808eea307.png)

**Comment by blackjackshellac** [comment]
Detect growing lines should do the trick.
