### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by comradekingu** [Keruspe/GPaste#329]
What is the preferred method of contributing translations?
Could the project be added on Hosted Weblate or similar?

**Comment by Keruspe** [comment]
Hi,

For now the translations have been submitted through github pull requests.
I'm not really familiar with any of the translation platforms but last time I checked those were pretty expensive, and GPaste is definitely not a commercial product nor backed by any company so...
But I'm fuly open to any platform which would be free for open source projects

**Comment by comradekingu** [comment]
There is a special plan for that https://hosted.weblate.org/hosting/
add https://hosted.weblate.org/user/kingu/ if you want help setting it up :)

**Comment by Keruspe** [comment]
@comradekingu thanks, greatly appreciated. Just added you

**Comment by Keruspe** [comment]
Pending approval but everything should be set up now!
