### ISSUE TITLE
marking active item as password does not work

### ISSUE THREAD

**Issue by kehomat** [Keruspe/GPaste#332]
Keyboard shortcut press `<ctrl><alt>s`  does not mark history item as password.
Every time there is a log entry `gpaste-daemon[34343]: g_paste_history_set_password: assertion 'todel' failed` in the syslog

gpaste-client version: GPaste 3.38.2
gnome-shell version: GNOME Shell 3.38.1

**Comment by Keruspe** [comment]
Thanks for the details, I should be able to fix that even without reproducing with those logs

**Comment by Keruspe** [comment]
Ohhh, indeed, I see what the problem is, fixing it

**Comment by Keruspe** [comment]
Will make a bugfix release later this week
