### ISSUE TITLE
Extension doesn't work in GNOME Shell 40.beta

### ISSUE THREAD

**Issue by jdoss** [Keruspe/GPaste#344]
Trying to use the extension on Fedora 34 results in the following stack trace. `gpaste-daemon` and `gpaste-ui` work well.

```
$ gnome-shell --version
GNOME Shell 40.beta
```

```
$ rpm -qa |grep gpaste
gpaste-libs-3.38.5-1.fc34.x86_64
gpaste-3.38.5-1.fc34.x86_64
gpaste-ui-3.38.5-1.fc34.x86_64
gnome-shell-extension-gpaste-3.38.5-1.fc34.noarch
```

```
Error: Requiring GPaste, version none: Requiring namespace 'Gtk' version '3.0', but '4.0' is already loaded

Stack trace:
  @/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/prefs.js:11:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:206:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by Keruspe** [comment]
Gtk4 port is in progress

**Comment by Keruspe** [comment]
Might be a little late for the official gnome 40 release but I hope to release it before April

**Comment by Keruspe** [comment]
Hum, now I'm very puzzled.

Is it just about the preferences, or is it about the whole extension?

I get the exact opposite message for the extension with my gtk4 port.

**Comment by jtojnar** [comment]
For me, it currently fails with

```
Error: No property margin on GPasteSettingsUiWidget

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
  buildPrefsWidget@/run/current-system/sw/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/prefs.js:25:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/nix/store/fwnkwvhwm3kqck4fhkc5y5z853radggg-gnome-shell-40.0/share/gnome-shell/.org.gnome.Shell.Extensions-wrapped:7:17
```

When attempting to open preferences. Though I had to change `mutter-clutter-7` in `configure.ac` to `mutter-clutter-8`.

**Comment by Keruspe** [comment]
@jtojnar yes that's "normal", haven't fixed this part yet.

But, this whole bug report, is it only for the preferences, or for the whole extension?

**Comment by Keruspe** [comment]
Long story short:

- gnome-shell doesn't support extensions using gtk4, only gtk3
- gnome-shell extension tool for prefs doesn't support extensions using gtk3, only gtk4
- GPaste shares a library between all its tools (including the extension and the prefs tool)
- A library cannot use both gtk3 and gtk4 at the same time
- GPaste used to have several libraries to avoid this kind of issues, but they have been merged as per debian packagers request, amongst other things.

I will release GPaste 3.40.0 really soon, with only a few differences from 3.38, with a placeholder for the extension preferences.

I will release a proper GPaste 40.0 during the summer.
