### ISSUE TITLE
[GPaste 3.40.1] Error in gnome extensions

### ISSUE THREAD

**Issue by mysticaltech** [Keruspe/GPaste#351]
Hello,  I was finally able to compile and install for OpenSuse Tumbletweed latest with Gnome 4, it works well, but the gnome extension doesn't, I get this error: 

`Requiring GPaste, version 1.0: Typelib file for namespace 'GPaste', version '1.0' not found`

Any ideas? 

_And thank you so much btw, I love this tool, just moved over from mac which I've been using a similar one, and it's been a life saver!_

**Comment by Keruspe** [comment]
Looks like gnome-shell cannot find some stuff installed by GPaste (probably
because it might be installed in /usr/local and it looks into /usr ?)
Namely it cannot find the gobject-introspection data required for the
JavaScript extension to use the C library

**Comment by mysticaltech** [comment]
Thanks @Keruspe. Finally, I removed everything, and did `sudo make uninstall` rebooted, then cloned from master, and redid the steps without using sudo. Used it as in the commands just for `sudo make install` and it worked 🎉

---

As a reference to others installing on OpenSuse Tumbleweed, here's the package's that were needed to compile, more or less (got it from my command history, so some may be overkill, but it should make it work):

```
sudo zypper install -t pattern devel_basis 
sudo zypper in gobject-introspection
sudo zypper in vala-devel
sudo zypper in glib
sudo zypper in libglib
sudo zypper in glib2
sudo zypper in gobject
sudo zypper in gio
sudo zypper in libglibmm-2_68-1
sudo zypper in glibc
sudo zypper in gtk2-devel
sudo zypper in gtk3
sudo zypper in gtk3-devel
sudo zypper in appstream-glib
sudo zypper in appstream-glib-devel
sudo zypper in gobject-introspection-devel 
sudo zypper in mutter mutter-devel gjs gjs-devel
```
