### ISSUE TITLE
[GPaste 3.40.1] Needed libs to compile on Fedora 34

### ISSUE THREAD

**Issue by mysticaltech** [Keruspe/GPaste#353]
Hey folks, this is just a share of info to make your life easier if you have to compile on Fedora.

_This is a shotgun approach, as I've just copied my command history, but it should install the necessary packages and more (probably overkill, and don't be shocked if some packages are not found). When installed, just follow the README where you will find the commands needed for compilation. If you already ran those before, and encountered errors, start fresh in a newly extracted folder after having installed the missing libraries below._

```
sudo dnf groupinstall "Development Tools" "Development Libraries"
sudo dnf install gettext-devel
sudo dnf install libtool
sudo dnf install gobject-introspection
sudo dnf install vala-devel
sudo dnf install gtk2-devel
sudo dnf install gtk3-devel
sudo dnf install gtk3
sudo dnf install appstream-glib-devel
sudo dnf install appstream-glib
sudo dnf install gobject-introspection-devel
sudo dnf install mutter mutter-devel gjs gjs-devel
sudo dnf install glib
sudo dnf install libglib
sudo dnf install glib2
sudo dnf install gobject gio libglibmm glibc
sudo dnf install appstream-util
sudo dnf install valac
sudo dnf install libappindicator3
sudo dnf install vala-tools
sudo dnf install appstream-glib
sudo dnf install libappstream-glib
sudo dnf install docbook-utils gettext-devel glib-devel gobject-introspection-devel gperf gtk-doc gtk3-devel json-glib-devel libarchive-devel libsoup-devel libstemmer-devel libuuid-devel libyaml-devel meson rpm-devel
sudo dnf install appstream
sudo dnf install appstream-glic
sudo dnf install appstream-devel
sudo dnf install libappstream-glib
sudo dnf install libappstream-glib-devel
sudo dnf install appstream-qt-devel
```

**Comment by Keruspe** [comment]
@mysticaltech I'd be more than happy to accept a PR listing this somewhere in the repository if you'd like

**Comment by mysticaltech** [comment]
Thanks @Keruspe, the problem is that it may be overkill hehe, probably a few unnecessary libs are being installed 'just in case'. Up to you, if you want, I could do a PR for both Fedora and OpenSuse.

**Comment by mysticaltech** [comment]
Ah, but you could filter the unnecessary ones out probably, as the app dev, correct?
