### ISSUE TITLE
gpaste-client 3.40.2 still shows UUIDs when I call “history” with “--use-index”

### ISSUE THREAD

**Issue by unclechu** [Keruspe/GPaste#359]
When I call `gpaste-client history --use-index` or `gpaste-client --use-index history` it still shows UUIDs.

> gpaste-client --version
GPaste 3.40.2

**Comment by unclechu** [comment]
I still have the issue with `GPaste 43.0`.

**Comment by yusufaktepe** [comment]
`history` option doesn't accept arguments. I think it's only available for `get`, `select`, `delete`, `replace`...

**Comment by Keruspe** [comment]
Releasing a fix tonight
