### ISSUE TITLE
(shell extension) Show history shortcut works while on a XWayland window but doesn't on Wayland

### ISSUE THREAD

**Issue by cpouldev** [Keruspe/GPaste#376]
I have Fedora 35-beta with the latest GNOME 41.

GPaste version is 3.42.0

While I am on an Xwayland window (eg a jetbrains editor), I can trigger the "Show history" popup normally with the shortcut (ctrl+alt+h or something else).

While I am on a Wayland window (eg firefox or terminal) it doesn't work and I have to manually trigger it using the mouse.

I'm not sure if it's related on this https://github.com/Keruspe/GPaste/issues/368

**Comment by Keruspe** [comment]
It is indeed related, but I found a loophole and will issue a new release shortly which should address this

**Comment by kapouer** [comment]
@Keruspe did you report this issue on [gnome-shell bts](https://gitlab.gnome.org/GNOME/gnome-shell/issues) ?

**Comment by Keruspe** [comment]
The thing that introduced the breakage introduces it by design. There's an issue to add a portal to manage that instead
