### ISSUE TITLE
It seems GPaste doesn't work on Ubuntu 22.04

### ISSUE THREAD

**Issue by larryw3i** [Keruspe/GPaste#387]
It seems GPaste doesn't work on Ubuntu 22.04.   
All  keyboard shortcuts couldn't trigger GPaste function, it prints following when I start `/usr/libexec/gpaste/gpaste-daemon` :  
```
(gpaste-daemon:30102): GPaste-WARNING **: 19:04:19.606: \
Couldn't grab keybindings with gnome-shell: \
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: \
The name org.gnome.Shell was not provided by any .service files
```

**Comment by Keruspe** [comment]
Are you running gnome-shell? Are you running X11 or wayland?

**Comment by larryw3i** [comment]
@Keruspe It doesn't work on Wayland.

**Comment by Keruspe** [comment]
Are you using gnome-shell?

**Comment by larryw3i** [comment]
![image](https://user-images.githubusercontent.com/24457116/154086074-0f73cc6e-5ecf-4563-9fee-3ac7c7ed4b70.png)
  
Yea! I used it.

**Comment by Keruspe** [comment]
It is installed, but is your session running on gnome-shell? The error message suggests it doesn't.

**Comment by larryw3i** [comment]
I'm not sure, but it works fine on x11, but keyboard shortcuts couldn't trigger it any more when I switch to Wayland.

**Comment by Keruspe** [comment]
Keyboards shortcut work only when running with gnome-shell, on wayland. On x11 they work even without gnome-shell. This is due to security limitations from the wayland ecosystem. Solutions are in the process of being designed for this (not by GPaste, it's a global problem)
