### ISSUE TITLE
unable to follow steps in readme

### ISSUE THREAD

**Issue by garryavx** [Keruspe/GPaste#390]
I cloned the repo, and in the readme it says to run ./autogen.sh and then ./configure --sysconfdir=/etc

these files dont exist. I searched the repo for them as well.

what am I missing?

**Comment by marv** [comment]
The autotools build system was recently dropped in favour of the meson based build system[1]

With meson the build steps are:
```
mkdir builddir
cd builddir
meson ..
ninja
```

[1] https://github.com/Keruspe/GPaste/commit/67b779b9a1c9385aadc5777ca694e3f305accfa8
