### ISSUE TITLE
soname for gpaste 42 is gpaste-2.so.0.0.0

### ISSUE THREAD

**Issue by kapouer** [Keruspe/GPaste#392]
That's confusing, especially since old versions of gpaste somewhat already used the gpaste-X.0 notation.
Couldn't this be simply `gpaste.so.42.1.0` ?

**Comment by Keruspe** [comment]
Older versions of GPaste had libgpaste.so not libgpaste-2.so

Also, 42.1.0 would be wrong in term of so naming.

Furthermore, changing it now would be a breaking change

**Comment by Keruspe** [comment]
GPaste 42 being the first version shipping libgpaste-2, anything else than 0.0.0 would be confusing imo
