### ISSUE TITLE
Question about license in data/appstream/org.gnome.GPaste.Ui.appdata.xml.in

### ISSUE THREAD

**Issue by kapouer** [Keruspe/GPaste#398]
[this line](https://github.com/Keruspe/GPaste/blob/e072a3dad9689693cc2fbf545f88d40961d65689/data/appstream/org.gnome.GPaste.Ui.appdata.xml.in#L9) mentions a CC-BY-SA-3.0 license, however it's not clear to what it applies.
To the [website links](http://www.imagination-land.org/tags/GPaste.html) ?
to the [image content](http://www.imagination-land.org/images/GPaste/3/Ui-1.png) ?

**Comment by pabs3** [comment]
IIRC metadata_license in AppStream files applies to the file itself, not anything else.

**Comment by kapouer** [comment]
oh, right.
