### ISSUE TITLE
String containing only spaces does not get saved?

### ISSUE THREAD

**Issue by nfejzic** [Keruspe/GPaste#415]
When I try to save string containing only spaces it does not get saved to clipboard.

For example: `echo "    " | gpaste-clipboard` does not store the `"    "` string.

Is this expected? Any way to force storing this?

**Comment by Keruspe** [comment]
Do you have the trimming feature enabled?

**Comment by nfejzic** [comment]
> Do you have the trimming feature enabled?

In my GUI it's off, but I installed GUI and `gpaste-client` separately through native package manager. I'm using Fedora Workstation 37, package manager is `dnf`. 

![image](https://user-images.githubusercontent.com/40841816/222924144-bdc022bf-2c2d-44cd-a937-4c844c390c8d.png)

Is there some other config option to enable or disable it?

**Comment by Keruspe** [comment]
No, that should be enough.

I'll check
