### ISSUE TITLE
[bug] dbus service not starting

### ISSUE THREAD

**Issue by werdahias** [Keruspe/GPaste#418]
OS: Debian sid
WM: wayfire
gpaste: 43-1

I have a debian sid system with openrc. The daemon doesn't start:
```
gpaste-client daemon-reexec

(gpaste-client:9932): GPaste-CRITICAL **: 11:14:22.984: Error calling StartServiceByName for org.gnome.GPaste: Process org.gnome.GPaste exited with status 1
```
running the daemon manually also doesn't work:
```

/usr/libexec/gpaste/gpaste-daemon

(gpaste-daemon:10413): Gtk-WARNING **: 11:19:26.543: cannot open display: :0
```

I run wayfire inside a dbus session.

**Comment by Keruspe** [comment]
GPaste requires a running X or Xwayland server

**Comment by werdahias** [comment]
ah, ok. is wayland support planned?

**Comment by Keruspe** [comment]
As soon as it is possible to monitor clipboard events on wayland, yes

**Comment by werdahias** [comment]
ok, thanks.
