### ISSUE TITLE
Support for Gnome 44

### ISSUE THREAD

**Issue by vwbusguy** [Keruspe/GPaste#419]
Gnome 44 is officially released and Fedora 38 Beta (which will be GA in a few weeks) already has it, but the current release of GPaste doesn't appear to support it yet.

![image](https://user-images.githubusercontent.com/5474941/227594642-43d31870-b9ce-4ba5-bf10-e612a4320bb6.png)

**Comment by Keruspe** [comment]
It’s actually already in git, I just need to issue an actual release

**Comment by vwbusguy** [comment]
Many thanks!  This is an extension I use every day and a major part of my Gnome experience.  Thank you so much for maintaining this.  I very much appreciate your work.

**Comment by Keruspe** [comment]
Thanks for the kind words 😊

**Comment by Keruspe** [comment]
Made the release yesterday, usually fedora is quite fast at shipping it afterwards
