### ISSUE TITLE
gpaste gnome-shell extention is not visable

### ISSUE THREAD

**Issue by ausil** [Keruspe/GPaste#425]
On my Fedora 38 desktop machine I do not see the gpaste gnome-shell extension. If I start the app, I can see it is turned on, and it works fine on Fedora 38 on my laptop. I am not sure the best way to debug what is happening to give you the information needed to understand what is going on.

gpaste-libs-44.0-1.fc38.aarch64
gpaste-44.0-1.fc38.aarch64
gpaste-ui-44.0-1.fc38.aarch64
gnome-shell-extension-gpaste-44.0-1.fc38.noarch
gpaste-bash-completion-44.0-1.fc38.aarch64
gpaste-zsh-completion-44.0-1.fc38.aarch64

**Comment by HNazmul-IV** [comment]
I went here to open that issue. but already opened. 
it also happening for me.  I had enabled gnome-shell-extension in preparence. but nothing happened.

**Comment by Keruspe** [comment]
Can you type `Alt-F2` then, in the box that appears run the `lg` command?
It should make an overlay appear. If you go to the extensions tab (top right corner of the overlay), you should see GPaste listed amongst others.
Can you double check it says `Enabled` there, and click on `show errors` to see if anything pops out?

**Comment by ausil** [comment]
it does not show up as enabled, and if I try to enable on the CLI its not enabled

```
[dennis@ryac ~]$ gnome-extensions list --enabled
[dennis@ryac ~]$ gnome-extensions enable GPaste@gnome-shell-extensions.gnome.org
[dennis@ryac ~]$ gnome-extensions list --enabled
[dennis@ryac ~]$ 

```

**Comment by HNazmul-IV** [comment]
> 

I just seen that there need be installed gnome-shell-extension-gpaste in system. otherwise it will not appear.. since I installed installed with `apt` it doesn't include `gnome-shell-extension-gpaste` by default.
