### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by yochananmarqos** [Keruspe/GPaste#426]
There are breaking changes which will require a separate release for 45 and <=44:

See https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by yochananmarqos** [comment]
I just tested on GNOME 45.beta. You forgot to bump `mutter-clutter` from 12 to 13 in the `meson.build`. I manually did that and the tray icon and application works fine.

However, opening the settings:

The settings of extension GPaste@gnome-shell-extensions.gnome.org had an error:
```
TypeError: Object is of type GPasteGtk.PreferencesWidget - cannot convert to AdwPreferencesPage
```

Stack trace:
```
fillPreferencesWindow@file:///usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/prefs.js:13:16
_loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:36:18
async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:21:14
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:12:4
OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by Keruspe** [comment]
Should all be in order now

**Comment by yochananmarqos** [comment]
Well, the Preferences work now. However, with GNOME 45.rc, clicking on the tray icon just says _(Couldn't connect to GPaste daemon)_.  Running `gpaste-client dr` reports it successfully reexecuted the daemon, but there's no change. This is with or without the AppIndicator and KStatusNotifierItem extension.

**Comment by yochananmarqos** [comment]
@Keruspe Oops, forgot to tag you just in case since the issue is closed.

**Comment by yochananmarqos** [comment]
How are you testing this? I just installed from the b1d0cbf commit and cannot enable the extension:

> Unable to load file from: file:///usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/actionButton.js (Error opening file /usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/actionButton.js: No such file or directory)

I'm using GNOME 45.rc with 45.0 packages trickling in on Manjaro (unstable branch) with the [FCGU](https://codeberg.org/fabiscafe/fcgu) repo.
