### ISSUE TITLE
gpaste-client window should have a cli flag to stay in the center of the screen and not open at mouse cursor

### ISSUE THREAD

**Issue by stefancocora** [Keruspe/GPaste#427]
Hi Kerupse

Thank you for creating such a useful clipboard manager.

I'm using the gpaste clipboard manager with i3wm where my windows are always maximized in their own screen location.

I know there has been a feature introduced to open the gpaste window at mouse cursor ( see https://github.com/Keruspe/GPaste/pull/394 ) 

That might work fine for desktop environment users but it works badly for window manager users.

Use case broken example:
If I have a terminal window full and I type at the bottom of the terminal window, when I call the gpaste window, it pops up at the mouse cursor, very low on the screen which isn't usable.
Most of the gpaste window is hidden and searching and or scrolling doesn't help because the text is also hidden. (see attached screen grab )

Please create a cli flag or a way to tell the gpaste window to pop up in the center of the screen to solve this issue.
![gpaste-clipboard-manager-wrong-position-2023-09-05-113532_3840x2160_scrot](https://github.com/Keruspe/GPaste/assets/281241/928cb4b1-b7cf-4e17-9d5d-307ee7a764d5)

**Comment by Keruspe** [comment]
Hi,

While I understand the idea, I don't think that's a behaviour you want to change that often, you most likely always want either one or the other.
Furthermore, the application is launched through dbus activation to follow gnome standards which would complicate this.

What do you think of having a setting key for this instead?

**Comment by stefancocora** [comment]
Hi,

I agree with your assessment `you most likely always want either one or the other.`


Do I understand what you're suggesting correctly,  having a `setting key`  would mean a setting key in a config file ?

This would work fine!

I wasn't aware that gpaste had a config file that it reads, I've only seen the GUI settings accessed through the 3 vertical dots, dreaded, nameless menu :)

**Comment by stefancocora** [comment]
Thank you!
