### ISSUE TITLE
Extension says could not connect to gpaste-daemon on GNOME 45

### ISSUE THREAD

**Issue by bbhtt** [Keruspe/GPaste#428]
Using an RPM built from https://github.com/Keruspe/GPaste/commit/734286a8bd76d3a76a9d5f2f1651b8be36be17f9 https://github.com/bbhtt/GPaste/releases/tag/master-gnome45

for GNOME 45 on Fedora 39 GNOME 45.rc It was working fine on GNOME 45 beta. Issue started after updating to 45.rc

Journalctl has these errors:

```
Sep 13 20:25:44 fedora gnome-shell[3313]: JS ERROR: TypeError: (intermediate value).Align is undefined
                                          _init@file:///usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/pageItem.js:18:13
                                          GPastePageItem@file:///usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/pageItem.js:14:4
                                          _addPage@file:///usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/pageSwitcher.js:69:18
                                          updateForSize@file:///usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/pageSwitcher.js:50:18
                                          _refresh/</<@file:///usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/indicator.js:259:45
                                          @resource:///org/gnome/shell/ui/init.js:21:20
Sep 13 20:25:44 fedora gnome-shell[3313]: JS ERROR: TypeError: (intermediate value).Align is undefined
                                          _init@file:///usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/pageItem.js:18:13
                                          GPastePageItem@file:///usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/pageItem.js:14:4
                                          _addPage@file:///usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/pageSwitcher.js:69:18
                                          updateForSize@file:///usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/pageSwitcher.js:50:18
                                          _refresh/</<@file:///usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/indicator.js:259:45
                                          @resource:///org/gnome/shell/ui/init.js:21:20
```

Gpaste itself launches and works fine

**Comment by Keruspe** [comment]
How reproductible is it? Does it still occur after a reboot ?
I run it smoothly on fedora 39 here

**Comment by bbhtt** [comment]
>  I run it smoothly on fedora 39 here

I think 45.rc isn't released to the stable repos, you need to enable `updates-testing` to get them. It was working in 45.beta which F39 has by default.

> How reproductible is it? Does it still occur after a reboot ?

Happened every time. It didn't work at all. I tried the gdb method on daemon but nothing. The daemon itself works

**Comment by Keruspe** [comment]
Right. Will enable updates-testing and fix it tonight.
Any pointers as to how to enable this to avoid me the searching ?

**Comment by bbhtt** [comment]
> Right. Will enable updates-testing and fix it tonight. Any pointers as to how to enable this to avoid me the searching ?

It's in GNOME software > menu > software repositories > Test updates

![image](https://github.com/Keruspe/GPaste/assets/62639087/65f33d34-dbac-46fd-9f36-a8a0ebde021e)


Thanks

**Comment by Keruspe** [comment]
Thanks, will fix and maybe release 45.rc tonight

**Comment by Keruspe** [comment]
Fwiw, it's caused by https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/b45e75c4b99934a8ef12179bd23b1019c0269dbc

We should be using Clutter.ActorAlign instead of St.Align if you want to give it a shot 🙂

**Comment by bbhtt** [comment]
> We should be using Clutter.ActorAlign instead of St.Align if you want to give it a shot 🙂

Thanks, not really familiar with shell/extensions but I opened a PR with what I think are the replacements.

And you are right it does fix the issue. I rebuilt my rpms to check.

**Comment by Keruspe** [comment]
Welcome to the contributors!
