### ISSUE TITLE
Unable to load actionButton.js

### ISSUE THREAD

**Issue by yochananmarqos** [Keruspe/GPaste#430]
I just installed from the b1d0cbf commit on GNOME 45.rc and cannot enable the extension:

> Unable to load file from: file:///usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/actionButton.js (Error opening file /usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/actionButton.js: No such file or directory)

**Comment by Keruspe** [comment]
Oh, you're totally right, ouch, it's missing from the build system and thus from the tarball

**Comment by Keruspe** [comment]
Just released GPaste 45
