### ISSUE TITLE
[security] The default of Save History should be disabled

### ISSUE THREAD

**Issue by attila-lendvai** [Keruspe/GPaste#442]
### context

the basic idea of the clipboard is that it's an ephemeral storage, not readable by any app without explicit user action. as such, it often contains passwords and other sensitive information in its regular use. saving the history in clear text increases the attack surface in at least two ways:

1. boot from a pen drive and steal the clipboard history (from any unencrypted installation, which is still too often the case).
2. any app that has disk access can steal the passwords, even if it has no access to the clipboard.

### request

please set the default value of the Save History setting to disabled to minimise any **unintended** exposure to these attacks.

**Comment by MartinNowak** [comment]
Passwords are skipped https://github.com/Keruspe/GPaste/blob/e712e68ab8f4c708d05c525dfcbf7e55d7a951c8/src/daemon/tmp/gpaste-file-backend.c#L83, but of course not every sensitive entry might be marked as password.

**Comment by attila-lendvai** [comment]
i've just found an older issue for the same: https://github.com/Keruspe/GPaste/issues/357

i'll close this and copy-paste my description into a comment there.
