### ISSUE TITLE
Indicator still displaying when screen in locked

### ISSUE THREAD

**Issue by ectomorphic** [Keruspe/GPaste#71]
Hi!
The indicator on the top-right is still displaying when the screen is locked, and all the information stored there is available without entering the password.
I am using Gome 3.10

Thanks!

**Comment by JPvRiel** [comment]
Noticed the same issue with gnome 3.16. If GPaste is enabled/installed for the first time, the current gnome shell lockscreen doesn't hide the icon and access to clipboard history is available from the lockscreen.

Failed to find a bug for this in gnome bugzilla:
* component 'lockscreen', keyword 'indicator': https://bugzilla.gnome.org/buglist.cgi?classification=Core&component=lock-screen&list_id=78234&product=gnome-shell&query_format=advanced&short_desc=indicator&short_desc_type=allwordssubstr
* component 'lockscreen', keyword 'extension': https://bugzilla.gnome.org/buglist.cgi?classification=Core&component=lock-screen&list_id=78234&product=gnome-shell&query_format=advanced&short_desc=extension&short_desc_type=allwordssubstr
 * only one old bug, alegidly fixed: https://bugzilla.gnome.org/show_bug.cgi?id=686763
* component 'extension', keyword 'lock' https://bugzilla.gnome.org/buglist.cgi?classification=Core&component=extensions&list_id=78236&product=gnome-shell&query_format=advanced&short_desc=lock&short_desc_type=allwordssubstr

Logged a new bug: https://bugzilla.gnome.org/show_bug.cgi?id=758498

**Comment by Keruspe** [comment]
If it's only on first install and doesn't reproduce afterwards, it's clearly a bug in gnome-shell and not GPaste.

A really sad bug though :/

**Comment by JPvRiel** [comment]
@Keruspe yip, hence I logged a bug upstream... It's a minor issue with an easy work around :-)

**Comment by fturco** [comment]
I noticed I still have this bug. Gpaste contents are displayed even when the screen is locked. I'm using GNOME 3.20.1 and Gpaste 3.20. My distro is Parabola.
