### ISSUE TITLE
Redesigning the GNOME-Shell extension

### ISSUE THREAD

**Issue by brunelli** [Keruspe/GPaste#89]
Hello!
I've been thinking about how we could give a better look to the GS extension, so I decided to turn my thoughts on images.
My idea is to keep the UI closer to what we see on GNOME 3.12/3.13.
So, I've created [this repository](https://github.com/camporez/gpaste-mockups) and posted some images in there. The README has comments about each of them.
@Keruspe, I would apreciate if you could give a look on it and tell me honestly what you think.
Cheers!

**Comment by Keruspe** [comment]
Sadly I had way less time than I expected for the 3.16 cycle. I'm currently working on a "gpaste ui" tool which aims to implement the above, but I had to reduce my goals for 3.16. It should be feature-equivalent with legacy statusicon/appindicator for 3.16 (and actually the status icon and the app indicator will use it by then).

Nothing but this should remain for 3.18 though, so I hope I'll finally be able to implement these designs :)

**Comment by ianbrunelli** [comment]
Awesome!

Please let me know if there's anything I can do to help :)

**Comment by Keruspe** [comment]
Ok, now that 3.16 is out, here is my roadmap:

- search feature in gpaste ui
- gnome-shell-search-provider (issue #95 )
- histories management in gpaste ui (matching your design)
- merge feature in gpaste ui
- more design integration for the release
- if enough time, a new replace feature to add edition facilities to gpaste ui

**Comment by ianbrunelli** [comment]
Looks good!

There are some points I would like to bring:

- IMHO the settings icon on the popup menu is not necessary, as we now have a "home" icon to open the UI and the settings are easily accessible from there.

- The icon to open the UI isn't very clear. I don't think the "home" is a good choice, for me the icon should say "Hey, if you click me I'll turn this popup into a window".

- Two desktop entries is too much, don't you think just a .desktop to open GPaste UI is enough?
Also, changing the name to only "GPaste" and giving it a proper icon (thus making it themeable) would be awesome.

I really like the idea of GPaste UI, and I'll look again at my designs later and think on a way to better integrate history view + management + settings.

**Comment by Keruspe** [comment]
Hi,

I didn't have a lot of time for this, but I implemented a few features in gpaste-ui for 3.18.

Looking forward to make it pretty for the next release!

**Comment by ianbrunelli** [comment]
I am running the version from master and I really like it. I was thinking we could borrow some design decisions from GNOME Logs and implement it on GPaste UI.

**Comment by Keruspe** [comment]
I think most of this is ok now, probably better create one issue per thing that's missing now
