### ISSUE TITLE
gpaste could be a gnome-shell search provider for the clipboard history

### ISSUE THREAD

**Issue by kapouer** [Keruspe/GPaste#95]
the kind of provider that gets searched when typing in Activities view,
and be enabled/disabled in the Search control panel.

**Comment by Keruspe** [comment]
For your information, I have some fairly advanced wip for this. It baiscally works, just needs some polishing.

**Comment by Keruspe** [comment]
Just pushed it

**Comment by ianbrunelli** [comment]
Any way to make it display more characters?

I have `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.` on my clipboard and the search results has some horizontal space that could be used:

![captura de tela de 2015-06-12 20-04-50](https://cloud.githubusercontent.com/assets/5755892/8141567/44e3b824-113f-11e5-94f5-3c35b50f7a1f.png)

**Comment by Keruspe** [comment]
Can you open a new issue for this ?
